// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: management.proto

package management_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ALBUM  EntryType = 0
	EntryType_SONG   EntryType = 1
	EntryType_ARTIST EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ALBUM",
		1: "SONG",
		2: "ARTIST",
	}
	EntryType_value = map[string]int32{
		"ALBUM":  0,
		"SONG":   1,
		"ARTIST": 2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_management_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_management_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           string                 `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Percentage    float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *Progress) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Progress) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Progress) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type FoldersMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []string               `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoldersMessage) Reset() {
	*x = FoldersMessage{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoldersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoldersMessage) ProtoMessage() {}

func (x *FoldersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoldersMessage.ProtoReflect.Descriptor instead.
func (*FoldersMessage) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *FoldersMessage) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

type RegisteredMountMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredMountMessage) Reset() {
	*x = RegisteredMountMessage{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredMountMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredMountMessage) ProtoMessage() {}

func (x *RegisteredMountMessage) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredMountMessage.ProtoReflect.Descriptor instead.
func (*RegisteredMountMessage) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *RegisteredMountMessage) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *IdMessage) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PathMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMessage) Reset() {
	*x = PathMessage{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMessage) ProtoMessage() {}

func (x *PathMessage) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMessage.ProtoReflect.Descriptor instead.
func (*PathMessage) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *PathMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	StartSeparator *string                `protobuf:"bytes,2,opt,name=start_separator,json=startSeparator,proto3,oneof" json:"start_separator,omitempty"`
	EndSeparator   *string                `protobuf:"bytes,3,opt,name=end_separator,json=endSeparator,proto3,oneof" json:"end_separator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetStartSeparator() string {
	if x != nil && x.StartSeparator != nil {
		return *x.StartSeparator
	}
	return ""
}

func (x *SearchRequest) GetEndSeparator() string {
	if x != nil && x.EndSeparator != nil {
		return *x.EndSeparator
	}
	return ""
}

type LookupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntryType      EntryType              `protobuf:"varint,1,opt,name=entry_type,json=entryType,proto3,enum=platune.management.v1.EntryType" json:"entry_type,omitempty"`
	CorrelationIds []int64                `protobuf:"varint,2,rep,packed,name=correlation_ids,json=correlationIds,proto3" json:"correlation_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{6}
}

func (x *LookupRequest) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_ALBUM
}

func (x *LookupRequest) GetCorrelationIds() []int64 {
	if x != nil {
		return x.CorrelationIds
	}
	return nil
}

type SongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *LookupEntry           `protobuf:"bytes,1,opt,name=song,proto3,oneof" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongResponse) Reset() {
	*x = SongResponse{}
	mi := &file_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongResponse) ProtoMessage() {}

func (x *SongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongResponse.ProtoReflect.Descriptor instead.
func (*SongResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{7}
}

func (x *SongResponse) GetSong() *LookupEntry {
	if x != nil {
		return x.Song
	}
	return nil
}

type AlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AlbumEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumResponse) Reset() {
	*x = AlbumResponse{}
	mi := &file_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumResponse) ProtoMessage() {}

func (x *AlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumResponse.ProtoReflect.Descriptor instead.
func (*AlbumResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{8}
}

func (x *AlbumResponse) GetEntries() []*AlbumEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AlbumEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         string                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	AlbumId       int64                  `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	AlbumArtist   string                 `protobuf:"bytes,3,opt,name=album_artist,json=albumArtist,proto3" json:"album_artist,omitempty"`
	AlbumArtistId int64                  `protobuf:"varint,4,opt,name=album_artist_id,json=albumArtistId,proto3" json:"album_artist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumEntry) Reset() {
	*x = AlbumEntry{}
	mi := &file_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumEntry) ProtoMessage() {}

func (x *AlbumEntry) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumEntry.ProtoReflect.Descriptor instead.
func (*AlbumEntry) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{9}
}

func (x *AlbumEntry) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *AlbumEntry) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AlbumEntry) GetAlbumArtist() string {
	if x != nil {
		return x.AlbumArtist
	}
	return ""
}

func (x *AlbumEntry) GetAlbumArtistId() int64 {
	if x != nil {
		return x.AlbumArtistId
	}
	return 0
}

type LookupEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	AlbumArtist   string                 `protobuf:"bytes,2,opt,name=album_artist,json=albumArtist,proto3" json:"album_artist,omitempty"`
	Album         string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	Song          string                 `protobuf:"bytes,4,opt,name=song,proto3" json:"song,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Track         int64                  `protobuf:"varint,6,opt,name=track,proto3" json:"track,omitempty"`
	Duration      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupEntry) Reset() {
	*x = LookupEntry{}
	mi := &file_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupEntry) ProtoMessage() {}

func (x *LookupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupEntry.ProtoReflect.Descriptor instead.
func (*LookupEntry) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{10}
}

func (x *LookupEntry) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *LookupEntry) GetAlbumArtist() string {
	if x != nil {
		return x.AlbumArtist
	}
	return ""
}

func (x *LookupEntry) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *LookupEntry) GetSong() string {
	if x != nil {
		return x.Song
	}
	return ""
}

func (x *LookupEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LookupEntry) GetTrack() int64 {
	if x != nil {
		return x.Track
	}
	return 0
}

func (x *LookupEntry) GetDuration() *timestamppb.Timestamp {
	if x != nil {
		return x.Duration
	}
	return nil
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LookupEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{11}
}

func (x *LookupResponse) GetEntries() []*LookupEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SearchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Entry          string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	EntryType      EntryType              `protobuf:"varint,2,opt,name=entry_type,json=entryType,proto3,enum=platune.management.v1.EntryType" json:"entry_type,omitempty"`
	Artist         *string                `protobuf:"bytes,3,opt,name=artist,proto3,oneof" json:"artist,omitempty"`
	CorrelationIds []int64                `protobuf:"varint,4,rep,packed,name=correlation_ids,json=correlationIds,proto3" json:"correlation_ids,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResult) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *SearchResult) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_ALBUM
}

func (x *SearchResult) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *SearchResult) GetCorrelationIds() []int64 {
	if x != nil {
		return x.CorrelationIds
	}
	return nil
}

func (x *SearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeletedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedResult) Reset() {
	*x = DeletedResult{}
	mi := &file_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedResult) ProtoMessage() {}

func (x *DeletedResult) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedResult.ProtoReflect.Descriptor instead.
func (*DeletedResult) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{14}
}

func (x *DeletedResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeletedResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeletedResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeletedResponse) Reset() {
	*x = GetDeletedResponse{}
	mi := &file_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeletedResponse) ProtoMessage() {}

func (x *GetDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeletedResponse.ProtoReflect.Descriptor instead.
func (*GetDeletedResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeletedResponse) GetResults() []*DeletedResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\x15platune.management.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\bProgress\x12\x10\n" +
	"\x03job\x18\x01 \x01(\tR\x03job\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\"*\n" +
	"\x0eFoldersMessage\x12\x18\n" +
	"\afolders\x18\x01 \x03(\tR\afolders\".\n" +
	"\x16RegisteredMountMessage\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\"\x1d\n" +
	"\tIdMessage\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"!\n" +
	"\vPathMessage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xa3\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12,\n" +
	"\x0fstart_separator\x18\x02 \x01(\tH\x00R\x0estartSeparator\x88\x01\x01\x12(\n" +
	"\rend_separator\x18\x03 \x01(\tH\x01R\fendSeparator\x88\x01\x01B\x12\n" +
	"\x10_start_separatorB\x10\n" +
	"\x0e_end_separator\"y\n" +
	"\rLookupRequest\x12?\n" +
	"\n" +
	"entry_type\x18\x01 \x01(\x0e2 .platune.management.v1.EntryTypeR\tentryType\x12'\n" +
	"\x0fcorrelation_ids\x18\x02 \x03(\x03R\x0ecorrelationIds\"T\n" +
	"\fSongResponse\x12;\n" +
	"\x04song\x18\x01 \x01(\v2\".platune.management.v1.LookupEntryH\x00R\x04song\x88\x01\x01B\a\n" +
	"\x05_song\"L\n" +
	"\rAlbumResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.platune.management.v1.AlbumEntryR\aentries\"\x88\x01\n" +
	"\n" +
	"AlbumEntry\x12\x14\n" +
	"\x05album\x18\x01 \x01(\tR\x05album\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\x03R\aalbumId\x12!\n" +
	"\falbum_artist\x18\x03 \x01(\tR\valbumArtist\x12&\n" +
	"\x0falbum_artist_id\x18\x04 \x01(\x03R\ralbumArtistId\"\xd4\x01\n" +
	"\vLookupEntry\x12\x16\n" +
	"\x06artist\x18\x01 \x01(\tR\x06artist\x12!\n" +
	"\falbum_artist\x18\x02 \x01(\tR\valbumArtist\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x12\n" +
	"\x04song\x18\x04 \x01(\tR\x04song\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x14\n" +
	"\x05track\x18\x06 \x01(\x03R\x05track\x126\n" +
	"\bduration\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bduration\"N\n" +
	"\x0eLookupResponse\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".platune.management.v1.LookupEntryR\aentries\"\xd8\x01\n" +
	"\fSearchResult\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\x12?\n" +
	"\n" +
	"entry_type\x18\x02 \x01(\x0e2 .platune.management.v1.EntryTypeR\tentryType\x12\x1b\n" +
	"\x06artist\x18\x03 \x01(\tH\x00R\x06artist\x88\x01\x01\x12'\n" +
	"\x0fcorrelation_ids\x18\x04 \x03(\x03R\x0ecorrelationIds\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescriptionB\t\n" +
	"\a_artist\"O\n" +
	"\x0eSearchResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.platune.management.v1.SearchResultR\aresults\"3\n" +
	"\rDeletedResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"T\n" +
	"\x12GetDeletedResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.platune.management.v1.DeletedResultR\aresults*,\n" +
	"\tEntryType\x12\t\n" +
	"\x05ALBUM\x10\x00\x12\b\n" +
	"\x04SONG\x10\x01\x12\n" +
	"\n" +
	"\x06ARTIST\x10\x022\xf3\a\n" +
	"\n" +
	"Management\x12;\n" +
	"\tStartSync\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\n" +
	"AddFolders\x12%.platune.management.v1.FoldersMessage\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rGetAllFolders\x12\x16.google.protobuf.Empty\x1a%.platune.management.v1.FoldersMessage\x12V\n" +
	"\rRegisterMount\x12-.platune.management.v1.RegisteredMountMessage\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x12GetRegisteredMount\x12\x16.google.protobuf.Empty\x1a-.platune.management.v1.RegisteredMountMessage\x12Y\n" +
	"\x06Search\x12$.platune.management.v1.SearchRequest\x1a%.platune.management.v1.SearchResponse(\x010\x01\x12U\n" +
	"\x06Lookup\x12$.platune.management.v1.LookupRequest\x1a%.platune.management.v1.LookupResponse\x12X\n" +
	"\rGetSongByPath\x12\".platune.management.v1.PathMessage\x1a#.platune.management.v1.SongResponse\x12a\n" +
	"\x17GetAlbumsByAlbumArtists\x12 .platune.management.v1.IdMessage\x1a$.platune.management.v1.AlbumResponse\x12O\n" +
	"\n" +
	"GetDeleted\x12\x16.google.protobuf.Empty\x1a).platune.management.v1.GetDeletedResponse\x12H\n" +
	"\fDeleteTracks\x12 .platune.management.v1.IdMessage\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fSubscribeEvents\x12\x16.google.protobuf.Empty\x1a\x1f.platune.management.v1.Progress0\x01Br\n" +
	"\x15platune.management.v1B\x0fManagementProtoP\x01Z.github.com/aschey/platune/client/management_v1\xaa\x02\x15Platune.Management.V1b\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_management_proto_goTypes = []any{
	(EntryType)(0),                 // 0: platune.management.v1.EntryType
	(*Progress)(nil),               // 1: platune.management.v1.Progress
	(*FoldersMessage)(nil),         // 2: platune.management.v1.FoldersMessage
	(*RegisteredMountMessage)(nil), // 3: platune.management.v1.RegisteredMountMessage
	(*IdMessage)(nil),              // 4: platune.management.v1.IdMessage
	(*PathMessage)(nil),            // 5: platune.management.v1.PathMessage
	(*SearchRequest)(nil),          // 6: platune.management.v1.SearchRequest
	(*LookupRequest)(nil),          // 7: platune.management.v1.LookupRequest
	(*SongResponse)(nil),           // 8: platune.management.v1.SongResponse
	(*AlbumResponse)(nil),          // 9: platune.management.v1.AlbumResponse
	(*AlbumEntry)(nil),             // 10: platune.management.v1.AlbumEntry
	(*LookupEntry)(nil),            // 11: platune.management.v1.LookupEntry
	(*LookupResponse)(nil),         // 12: platune.management.v1.LookupResponse
	(*SearchResult)(nil),           // 13: platune.management.v1.SearchResult
	(*SearchResponse)(nil),         // 14: platune.management.v1.SearchResponse
	(*DeletedResult)(nil),          // 15: platune.management.v1.DeletedResult
	(*GetDeletedResponse)(nil),     // 16: platune.management.v1.GetDeletedResponse
	(*timestamppb.Timestamp)(nil),  // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 18: google.protobuf.Empty
}
var file_management_proto_depIdxs = []int32{
	0,  // 0: platune.management.v1.LookupRequest.entry_type:type_name -> platune.management.v1.EntryType
	11, // 1: platune.management.v1.SongResponse.song:type_name -> platune.management.v1.LookupEntry
	10, // 2: platune.management.v1.AlbumResponse.entries:type_name -> platune.management.v1.AlbumEntry
	17, // 3: platune.management.v1.LookupEntry.duration:type_name -> google.protobuf.Timestamp
	11, // 4: platune.management.v1.LookupResponse.entries:type_name -> platune.management.v1.LookupEntry
	0,  // 5: platune.management.v1.SearchResult.entry_type:type_name -> platune.management.v1.EntryType
	13, // 6: platune.management.v1.SearchResponse.results:type_name -> platune.management.v1.SearchResult
	15, // 7: platune.management.v1.GetDeletedResponse.results:type_name -> platune.management.v1.DeletedResult
	18, // 8: platune.management.v1.Management.StartSync:input_type -> google.protobuf.Empty
	2,  // 9: platune.management.v1.Management.AddFolders:input_type -> platune.management.v1.FoldersMessage
	18, // 10: platune.management.v1.Management.GetAllFolders:input_type -> google.protobuf.Empty
	3,  // 11: platune.management.v1.Management.RegisterMount:input_type -> platune.management.v1.RegisteredMountMessage
	18, // 12: platune.management.v1.Management.GetRegisteredMount:input_type -> google.protobuf.Empty
	6,  // 13: platune.management.v1.Management.Search:input_type -> platune.management.v1.SearchRequest
	7,  // 14: platune.management.v1.Management.Lookup:input_type -> platune.management.v1.LookupRequest
	5,  // 15: platune.management.v1.Management.GetSongByPath:input_type -> platune.management.v1.PathMessage
	4,  // 16: platune.management.v1.Management.GetAlbumsByAlbumArtists:input_type -> platune.management.v1.IdMessage
	18, // 17: platune.management.v1.Management.GetDeleted:input_type -> google.protobuf.Empty
	4,  // 18: platune.management.v1.Management.DeleteTracks:input_type -> platune.management.v1.IdMessage
	18, // 19: platune.management.v1.Management.SubscribeEvents:input_type -> google.protobuf.Empty
	18, // 20: platune.management.v1.Management.StartSync:output_type -> google.protobuf.Empty
	18, // 21: platune.management.v1.Management.AddFolders:output_type -> google.protobuf.Empty
	2,  // 22: platune.management.v1.Management.GetAllFolders:output_type -> platune.management.v1.FoldersMessage
	18, // 23: platune.management.v1.Management.RegisterMount:output_type -> google.protobuf.Empty
	3,  // 24: platune.management.v1.Management.GetRegisteredMount:output_type -> platune.management.v1.RegisteredMountMessage
	14, // 25: platune.management.v1.Management.Search:output_type -> platune.management.v1.SearchResponse
	12, // 26: platune.management.v1.Management.Lookup:output_type -> platune.management.v1.LookupResponse
	8,  // 27: platune.management.v1.Management.GetSongByPath:output_type -> platune.management.v1.SongResponse
	9,  // 28: platune.management.v1.Management.GetAlbumsByAlbumArtists:output_type -> platune.management.v1.AlbumResponse
	16, // 29: platune.management.v1.Management.GetDeleted:output_type -> platune.management.v1.GetDeletedResponse
	18, // 30: platune.management.v1.Management.DeleteTracks:output_type -> google.protobuf.Empty
	1,  // 31: platune.management.v1.Management.SubscribeEvents:output_type -> platune.management.v1.Progress
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	file_management_proto_msgTypes[5].OneofWrappers = []any{}
	file_management_proto_msgTypes[7].OneofWrappers = []any{}
	file_management_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		EnumInfos:         file_management_proto_enumTypes,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
