// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/aschey/platune/cli/internal"
)

// Injectors from wire.go:

func InitializeCommands() commands {
	platuneClient := internal.NewPlatuneClient()
	cmdPauseCmd := newPauseCmd(platuneClient)
	cmdResumeCmd := newResumeCmd(platuneClient)
	cmdCommands := commands{
		pause:  cmdPauseCmd,
		resume: cmdResumeCmd,
	}
	return cmdCommands
}

// wire.go:

type commands struct {
	pause  pauseCmd
	resume resumeCmd
}
