// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package queue

import (
	"github.com/aschey/platune/cli/internal"
)

// Injectors from wire.go:

func InitializeQueueCommand(playerClient *internal.PlayerClient, managementClient *internal.ManagementClient) QueueCmd {
	search := internal.NewSearch(managementClient)
	queueAddQueueCmd := newAddQueueCmd(playerClient, managementClient, search)
	queueCommands := commands{
		add: queueAddQueueCmd,
	}
	queueCmd := newQueueCmd(queueCommands)
	return queueCmd
}
