import { Theme } from './theme';
import { Colors } from '@blueprintjs/core';

export const darkTheme: Theme = {
  intentPrimary: Colors.BLUE3,
  intentSuccess: Colors.GREEN3,
  intentWarning: Colors.ORANGE3,
  intentDanger: Colors.RED3,
  backgroundMain: Colors.DARK_GRAY4,
  backgroundSecondary: '#334654',
  textMain: Colors.LIGHT_GRAY2,
  textSecondary: Colors.GRAY5,
  textPrimary: Colors.BLUE5,
  textSuccess: Colors.GREEN5,
  textWarning: Colors.ORANGE5,
  textDanger: Colors.RED5,
  tableBackground: Colors.DARK_GRAY4,
  gridStripe1: '#334554',
  gridStripe2: '#2c3d4a',
  navbarBackground: Colors.DARK_GRAY3,
  dialogBackground: Colors.DARK_GRAY3,
  buttonBackground: Colors.DARK_GRAY5,
  gridSelectedBackground: '#1c5691',
  gridSelectedShadow: '#131e29',
  playingRowBackground: Colors.GREEN3,
  windowControlsColor: '#69848a',
  songTimeColor: '#92c3e0',
  visualizerColor: '#2b65e3',
  volumeSliderColor: Colors.GRAY5,
  songProgressColor1: Colors.BLUE5,
  songProgressColor2: Colors.BLUE5,
  omnibarBackground: Colors.DARK_GRAY1,
  suggestedTagColors: [
    '#137CBD',
    '#4580E6',
    '#29A634',
    '#D99E0B',
    '#0F9960',
    '#AD99FF',
    '#728C23',
    '#D9822B',
    '#DB3737',
    '#DB2C6F',
    '#96622D',
    '#008075',
    '#D13913',
    '#C274C2',
  ],
};
