// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: player_rpc.proto

package platune

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_START_QUEUE   Event = 0
	Event_QUEUE_UPDATED Event = 1
	Event_STOP          Event = 2
	Event_PAUSE         Event = 3
	Event_RESUME        Event = 4
	Event_ENDED         Event = 5
	Event_NEXT          Event = 6
	Event_PREVIOUS      Event = 7
	Event_SET_VOLUME    Event = 8
	Event_SEEK          Event = 9
	Event_QUEUE_ENDED   Event = 10
	Event_POSITION      Event = 11
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0:  "START_QUEUE",
		1:  "QUEUE_UPDATED",
		2:  "STOP",
		3:  "PAUSE",
		4:  "RESUME",
		5:  "ENDED",
		6:  "NEXT",
		7:  "PREVIOUS",
		8:  "SET_VOLUME",
		9:  "SEEK",
		10: "QUEUE_ENDED",
		11: "POSITION",
	}
	Event_value = map[string]int32{
		"START_QUEUE":   0,
		"QUEUE_UPDATED": 1,
		"STOP":          2,
		"PAUSE":         3,
		"RESUME":        4,
		"ENDED":         5,
		"NEXT":          6,
		"PREVIOUS":      7,
		"SET_VOLUME":    8,
		"SEEK":          9,
		"QUEUE_ENDED":   10,
		"POSITION":      11,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_player_rpc_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_player_rpc_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{0}
}

type PlayerStatus int32

const (
	PlayerStatus_PLAYING PlayerStatus = 0
	PlayerStatus_STOPPED PlayerStatus = 1
	PlayerStatus_PAUSED  PlayerStatus = 2
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYING",
		1: "STOPPED",
		2: "PAUSED",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYING": 0,
		"STOPPED": 1,
		"PAUSED":  2,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_player_rpc_proto_enumTypes[1].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_player_rpc_proto_enumTypes[1]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{1}
}

type SeekMode int32

const (
	SeekMode_FORWARD  SeekMode = 0
	SeekMode_BACKWARD SeekMode = 1
	SeekMode_ABSOLUTE SeekMode = 2
)

// Enum value maps for SeekMode.
var (
	SeekMode_name = map[int32]string{
		0: "FORWARD",
		1: "BACKWARD",
		2: "ABSOLUTE",
	}
	SeekMode_value = map[string]int32{
		"FORWARD":  0,
		"BACKWARD": 1,
		"ABSOLUTE": 2,
	}
)

func (x SeekMode) Enum() *SeekMode {
	p := new(SeekMode)
	*p = x
	return p
}

func (x SeekMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeekMode) Descriptor() protoreflect.EnumDescriptor {
	return file_player_rpc_proto_enumTypes[2].Descriptor()
}

func (SeekMode) Type() protoreflect.EnumType {
	return &file_player_rpc_proto_enumTypes[2]
}

func (x SeekMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeekMode.Descriptor instead.
func (SeekMode) EnumDescriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{2}
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []string               `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_player_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *QueueRequest) GetQueue() []string {
	if x != nil {
		return x.Queue
	}
	return nil
}

type AddToQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []string               `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToQueueRequest) Reset() {
	*x = AddToQueueRequest{}
	mi := &file_player_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToQueueRequest) ProtoMessage() {}

func (x *AddToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToQueueRequest.ProtoReflect.Descriptor instead.
func (*AddToQueueRequest) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *AddToQueueRequest) GetSongs() []string {
	if x != nil {
		return x.Songs
	}
	return nil
}

type SeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *durationpb.Duration   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Mode          SeekMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=player_rpc.SeekMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekRequest) Reset() {
	*x = SeekRequest{}
	mi := &file_player_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekRequest) ProtoMessage() {}

func (x *SeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekRequest.ProtoReflect.Descriptor instead.
func (*SeekRequest) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *SeekRequest) GetTime() *durationpb.Duration {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *SeekRequest) GetMode() SeekMode {
	if x != nil {
		return x.Mode
	}
	return SeekMode_FORWARD
}

type SetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        float32                `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVolumeRequest) Reset() {
	*x = SetVolumeRequest{}
	mi := &file_player_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeRequest) ProtoMessage() {}

func (x *SetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeRequest.ProtoReflect.Descriptor instead.
func (*SetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *SetVolumeRequest) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type EventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event Event                  `protobuf:"varint,1,opt,name=event,proto3,enum=player_rpc.Event" json:"event,omitempty"`
	// Types that are valid to be assigned to EventPayload:
	//
	//	*EventResponse_State
	//	*EventResponse_SeekData
	//	*EventResponse_Progress
	EventPayload  isEventResponse_EventPayload `protobuf_oneof:"event_payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_player_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *EventResponse) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_START_QUEUE
}

func (x *EventResponse) GetEventPayload() isEventResponse_EventPayload {
	if x != nil {
		return x.EventPayload
	}
	return nil
}

func (x *EventResponse) GetState() *State {
	if x != nil {
		if x, ok := x.EventPayload.(*EventResponse_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *EventResponse) GetSeekData() *SeekResponse {
	if x != nil {
		if x, ok := x.EventPayload.(*EventResponse_SeekData); ok {
			return x.SeekData
		}
	}
	return nil
}

func (x *EventResponse) GetProgress() *PositionResponse {
	if x != nil {
		if x, ok := x.EventPayload.(*EventResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isEventResponse_EventPayload interface {
	isEventResponse_EventPayload()
}

type EventResponse_State struct {
	State *State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type EventResponse_SeekData struct {
	SeekData *SeekResponse `protobuf:"bytes,3,opt,name=seek_data,json=seekData,proto3,oneof"`
}

type EventResponse_Progress struct {
	Progress *PositionResponse `protobuf:"bytes,4,opt,name=progress,proto3,oneof"`
}

func (*EventResponse_State) isEventResponse_EventPayload() {}

func (*EventResponse_SeekData) isEventResponse_EventPayload() {}

func (*EventResponse_Progress) isEventResponse_EventPayload() {}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []string               `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	QueuePosition uint32                 `protobuf:"varint,2,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	Volume        float32                `protobuf:"fixed32,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_player_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *State) GetQueue() []string {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *State) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *State) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *durationpb.Duration   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	RetrievalTime *durationpb.Duration   `protobuf:"bytes,2,opt,name=retrieval_time,json=retrievalTime,proto3" json:"retrieval_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_player_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *PositionResponse) GetPosition() *durationpb.Duration {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PositionResponse) GetRetrievalTime() *durationpb.Duration {
	if x != nil {
		return x.RetrievalTime
	}
	return nil
}

type SeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SeekMillis    uint64                 `protobuf:"varint,2,opt,name=seek_millis,json=seekMillis,proto3" json:"seek_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekResponse) Reset() {
	*x = SeekResponse{}
	mi := &file_player_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekResponse) ProtoMessage() {}

func (x *SeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekResponse.ProtoReflect.Descriptor instead.
func (*SeekResponse) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *SeekResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SeekResponse) GetSeekMillis() uint64 {
	if x != nil {
		return x.SeekMillis
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PlayerStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=player_rpc.PlayerStatus" json:"status,omitempty"`
	Progress      *PositionResponse      `protobuf:"bytes,2,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	CurrentSong   *string                `protobuf:"bytes,3,opt,name=current_song,json=currentSong,proto3,oneof" json:"current_song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_player_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYING
}

func (x *StatusResponse) GetProgress() *PositionResponse {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *StatusResponse) GetCurrentSong() string {
	if x != nil && x.CurrentSong != nil {
		return *x.CurrentSong
	}
	return ""
}

type DevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []string               `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicesResponse) Reset() {
	*x = DevicesResponse{}
	mi := &file_player_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesResponse) ProtoMessage() {}

func (x *DevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesResponse.ProtoReflect.Descriptor instead.
func (*DevicesResponse) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *DevicesResponse) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SetOutputDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *string                `protobuf:"bytes,1,opt,name=device,proto3,oneof" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutputDeviceRequest) Reset() {
	*x = SetOutputDeviceRequest{}
	mi := &file_player_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputDeviceRequest) ProtoMessage() {}

func (x *SetOutputDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutputDeviceRequest.ProtoReflect.Descriptor instead.
func (*SetOutputDeviceRequest) Descriptor() ([]byte, []int) {
	return file_player_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *SetOutputDeviceRequest) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

var File_player_rpc_proto protoreflect.FileDescriptor

const file_player_rpc_proto_rawDesc = "" +
	"\n" +
	"\x10player_rpc.proto\x12\n" +
	"player_rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\"$\n" +
	"\fQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x03(\tR\x05queue\")\n" +
	"\x11AddToQueueRequest\x12\x14\n" +
	"\x05songs\x18\x01 \x03(\tR\x05songs\"f\n" +
	"\vSeekRequest\x12-\n" +
	"\x04time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x04time\x12(\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x14.player_rpc.SeekModeR\x04mode\"*\n" +
	"\x10SetVolumeRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\x02R\x06volume\"\xe9\x01\n" +
	"\rEventResponse\x12'\n" +
	"\x05event\x18\x01 \x01(\x0e2\x11.player_rpc.EventR\x05event\x12)\n" +
	"\x05state\x18\x02 \x01(\v2\x11.player_rpc.StateH\x00R\x05state\x127\n" +
	"\tseek_data\x18\x03 \x01(\v2\x18.player_rpc.SeekResponseH\x00R\bseekData\x12:\n" +
	"\bprogress\x18\x04 \x01(\v2\x1c.player_rpc.PositionResponseH\x00R\bprogressB\x0f\n" +
	"\revent_payload\"\\\n" +
	"\x05State\x12\x14\n" +
	"\x05queue\x18\x01 \x03(\tR\x05queue\x12%\n" +
	"\x0equeue_position\x18\x02 \x01(\rR\rqueuePosition\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x02R\x06volume\"\x8b\x01\n" +
	"\x10PositionResponse\x125\n" +
	"\bposition\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bposition\x12@\n" +
	"\x0eretrieval_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rretrievalTime\"X\n" +
	"\fSeekResponse\x12'\n" +
	"\x05state\x18\x01 \x01(\v2\x11.player_rpc.StateR\x05state\x12\x1f\n" +
	"\vseek_millis\x18\x02 \x01(\x04R\n" +
	"seekMillis\"\xc7\x01\n" +
	"\x0eStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.player_rpc.PlayerStatusR\x06status\x12=\n" +
	"\bprogress\x18\x02 \x01(\v2\x1c.player_rpc.PositionResponseH\x00R\bprogress\x88\x01\x01\x12&\n" +
	"\fcurrent_song\x18\x03 \x01(\tH\x01R\vcurrentSong\x88\x01\x01B\v\n" +
	"\t_progressB\x0f\n" +
	"\r_current_song\"+\n" +
	"\x0fDevicesResponse\x12\x18\n" +
	"\adevices\x18\x01 \x03(\tR\adevices\"@\n" +
	"\x16SetOutputDeviceRequest\x12\x1b\n" +
	"\x06device\x18\x01 \x01(\tH\x00R\x06device\x88\x01\x01B\t\n" +
	"\a_device*\xa8\x01\n" +
	"\x05Event\x12\x0f\n" +
	"\vSTART_QUEUE\x10\x00\x12\x11\n" +
	"\rQUEUE_UPDATED\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\t\n" +
	"\x05PAUSE\x10\x03\x12\n" +
	"\n" +
	"\x06RESUME\x10\x04\x12\t\n" +
	"\x05ENDED\x10\x05\x12\b\n" +
	"\x04NEXT\x10\x06\x12\f\n" +
	"\bPREVIOUS\x10\a\x12\x0e\n" +
	"\n" +
	"SET_VOLUME\x10\b\x12\b\n" +
	"\x04SEEK\x10\t\x12\x0f\n" +
	"\vQUEUE_ENDED\x10\n" +
	"\x12\f\n" +
	"\bPOSITION\x10\v*4\n" +
	"\fPlayerStatus\x12\v\n" +
	"\aPLAYING\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02*3\n" +
	"\bSeekMode\x12\v\n" +
	"\aFORWARD\x10\x00\x12\f\n" +
	"\bBACKWARD\x10\x01\x12\f\n" +
	"\bABSOLUTE\x10\x022\x89\a\n" +
	"\x06Player\x12<\n" +
	"\bSetQueue\x12\x18.player_rpc.QueueRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"AddToQueue\x12\x1d.player_rpc.AddToQueueRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x05Pause\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06Resume\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06Toggle\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04Seek\x12\x17.player_rpc.SeekRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\tSetVolume\x12\x1c.player_rpc.SetVolumeRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Next\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bPrevious\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x10GetCurrentStatus\x12\x16.google.protobuf.Empty\x1a\x1a.player_rpc.StatusResponse\x12F\n" +
	"\x0fSubscribeEvents\x12\x16.google.protobuf.Empty\x1a\x19.player_rpc.EventResponse0\x01\x12H\n" +
	"\x11ListOutputDevices\x12\x16.google.protobuf.Empty\x1a\x1b.player_rpc.DevicesResponse\x12M\n" +
	"\x0fSetOutputDevice\x12\".player_rpc.SetOutputDeviceRequest\x1a\x16.google.protobuf.EmptyB6\n" +
	"\n" +
	"player.rpcB\vPlayerProtoP\x01Z\x19github.com/aschey/platuneb\x06proto3"

var (
	file_player_rpc_proto_rawDescOnce sync.Once
	file_player_rpc_proto_rawDescData []byte
)

func file_player_rpc_proto_rawDescGZIP() []byte {
	file_player_rpc_proto_rawDescOnce.Do(func() {
		file_player_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_rpc_proto_rawDesc), len(file_player_rpc_proto_rawDesc)))
	})
	return file_player_rpc_proto_rawDescData
}

var file_player_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_player_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_player_rpc_proto_goTypes = []any{
	(Event)(0),                     // 0: player_rpc.Event
	(PlayerStatus)(0),              // 1: player_rpc.PlayerStatus
	(SeekMode)(0),                  // 2: player_rpc.SeekMode
	(*QueueRequest)(nil),           // 3: player_rpc.QueueRequest
	(*AddToQueueRequest)(nil),      // 4: player_rpc.AddToQueueRequest
	(*SeekRequest)(nil),            // 5: player_rpc.SeekRequest
	(*SetVolumeRequest)(nil),       // 6: player_rpc.SetVolumeRequest
	(*EventResponse)(nil),          // 7: player_rpc.EventResponse
	(*State)(nil),                  // 8: player_rpc.State
	(*PositionResponse)(nil),       // 9: player_rpc.PositionResponse
	(*SeekResponse)(nil),           // 10: player_rpc.SeekResponse
	(*StatusResponse)(nil),         // 11: player_rpc.StatusResponse
	(*DevicesResponse)(nil),        // 12: player_rpc.DevicesResponse
	(*SetOutputDeviceRequest)(nil), // 13: player_rpc.SetOutputDeviceRequest
	(*durationpb.Duration)(nil),    // 14: google.protobuf.Duration
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_player_rpc_proto_depIdxs = []int32{
	14, // 0: player_rpc.SeekRequest.time:type_name -> google.protobuf.Duration
	2,  // 1: player_rpc.SeekRequest.mode:type_name -> player_rpc.SeekMode
	0,  // 2: player_rpc.EventResponse.event:type_name -> player_rpc.Event
	8,  // 3: player_rpc.EventResponse.state:type_name -> player_rpc.State
	10, // 4: player_rpc.EventResponse.seek_data:type_name -> player_rpc.SeekResponse
	9,  // 5: player_rpc.EventResponse.progress:type_name -> player_rpc.PositionResponse
	14, // 6: player_rpc.PositionResponse.position:type_name -> google.protobuf.Duration
	14, // 7: player_rpc.PositionResponse.retrieval_time:type_name -> google.protobuf.Duration
	8,  // 8: player_rpc.SeekResponse.state:type_name -> player_rpc.State
	1,  // 9: player_rpc.StatusResponse.status:type_name -> player_rpc.PlayerStatus
	9,  // 10: player_rpc.StatusResponse.progress:type_name -> player_rpc.PositionResponse
	3,  // 11: player_rpc.Player.SetQueue:input_type -> player_rpc.QueueRequest
	4,  // 12: player_rpc.Player.AddToQueue:input_type -> player_rpc.AddToQueueRequest
	15, // 13: player_rpc.Player.Pause:input_type -> google.protobuf.Empty
	15, // 14: player_rpc.Player.Stop:input_type -> google.protobuf.Empty
	15, // 15: player_rpc.Player.Resume:input_type -> google.protobuf.Empty
	15, // 16: player_rpc.Player.Toggle:input_type -> google.protobuf.Empty
	5,  // 17: player_rpc.Player.Seek:input_type -> player_rpc.SeekRequest
	6,  // 18: player_rpc.Player.SetVolume:input_type -> player_rpc.SetVolumeRequest
	15, // 19: player_rpc.Player.Next:input_type -> google.protobuf.Empty
	15, // 20: player_rpc.Player.Previous:input_type -> google.protobuf.Empty
	15, // 21: player_rpc.Player.GetCurrentStatus:input_type -> google.protobuf.Empty
	15, // 22: player_rpc.Player.SubscribeEvents:input_type -> google.protobuf.Empty
	15, // 23: player_rpc.Player.ListOutputDevices:input_type -> google.protobuf.Empty
	13, // 24: player_rpc.Player.SetOutputDevice:input_type -> player_rpc.SetOutputDeviceRequest
	15, // 25: player_rpc.Player.SetQueue:output_type -> google.protobuf.Empty
	15, // 26: player_rpc.Player.AddToQueue:output_type -> google.protobuf.Empty
	15, // 27: player_rpc.Player.Pause:output_type -> google.protobuf.Empty
	15, // 28: player_rpc.Player.Stop:output_type -> google.protobuf.Empty
	15, // 29: player_rpc.Player.Resume:output_type -> google.protobuf.Empty
	15, // 30: player_rpc.Player.Toggle:output_type -> google.protobuf.Empty
	15, // 31: player_rpc.Player.Seek:output_type -> google.protobuf.Empty
	15, // 32: player_rpc.Player.SetVolume:output_type -> google.protobuf.Empty
	15, // 33: player_rpc.Player.Next:output_type -> google.protobuf.Empty
	15, // 34: player_rpc.Player.Previous:output_type -> google.protobuf.Empty
	11, // 35: player_rpc.Player.GetCurrentStatus:output_type -> player_rpc.StatusResponse
	7,  // 36: player_rpc.Player.SubscribeEvents:output_type -> player_rpc.EventResponse
	12, // 37: player_rpc.Player.ListOutputDevices:output_type -> player_rpc.DevicesResponse
	15, // 38: player_rpc.Player.SetOutputDevice:output_type -> google.protobuf.Empty
	25, // [25:39] is the sub-list for method output_type
	11, // [11:25] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_player_rpc_proto_init() }
func file_player_rpc_proto_init() {
	if File_player_rpc_proto != nil {
		return
	}
	file_player_rpc_proto_msgTypes[4].OneofWrappers = []any{
		(*EventResponse_State)(nil),
		(*EventResponse_SeekData)(nil),
		(*EventResponse_Progress)(nil),
	}
	file_player_rpc_proto_msgTypes[8].OneofWrappers = []any{}
	file_player_rpc_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_rpc_proto_rawDesc), len(file_player_rpc_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_rpc_proto_goTypes,
		DependencyIndexes: file_player_rpc_proto_depIdxs,
		EnumInfos:         file_player_rpc_proto_enumTypes,
		MessageInfos:      file_player_rpc_proto_msgTypes,
	}.Build()
	File_player_rpc_proto = out.File
	file_player_rpc_proto_goTypes = nil
	file_player_rpc_proto_depIdxs = nil
}
