[package]
name = "platune-tray"
version = "0.1.0"
edition = "2024"

[dependencies]
daemon-slayer = { git = "https://github.com/aschey/daemon-slayer", rev = "b197fe9735c4d566f365cc6bf9271328b56dca46", features = [
  "tray",
  "client",
] }
tokio = { version = "1.44", features = ["rt-multi-thread", "sync"] }
souvlaki = { version = "0.8.2", default-features = false, features = [
  "use_zbus",
] }
platuned-client = { path = "../platuned/client/rust" }
tipsy = "0.4.0"
futures-util = "0.3"
