[unstable]
profile-rustflags = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.release]
#rustflags = ["-Zlocation-detail=none"]
codegen-units = 1
build-std = "std"
lto = true
panic = "abort"
strip = true
