// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mount

import (
	"github.com/aschey/platune/cli/internal"
)

// Injectors from wire.go:

func InitializeMountCommand(managementClient *internal.ManagementClient) MountCmd {
	mountGetMountCmd := newGetMountCmd(managementClient)
	mountSetMountCmd := newSetMountCmd(managementClient)
	mountCommands := commands{
		get: mountGetMountCmd,
		set: mountSetMountCmd,
	}
	mountCmd := newMountCmd(mountCommands)
	return mountCmd
}
