import { Theme } from './theme';
import { Colors } from '@blueprintjs/core';

export const lightTheme: Theme = {
  intentPrimary: Colors.BLUE3,
  intentSuccess: Colors.GREEN3,
  intentWarning: Colors.ORANGE3,
  intentDanger: Colors.RED3,
  backgroundMain: Colors.LIGHT_GRAY2,
  backgroundSecondary: Colors.LIGHT_GRAY3,
  textMain: Colors.DARK_GRAY1,
  textSecondary: Colors.GRAY1,
  textPrimary: Colors.BLUE3,
  textSuccess: Colors.GREEN3,
  textWarning: Colors.ORANGE3,
  textDanger: Colors.RED3,
  tableBackground: Colors.LIGHT_GRAY5,
  gridStripe1: '#e4e7eb',
  gridStripe2: '#d5e0e8',
  navbarBackground: Colors.GRAY5,
  dialogBackground: Colors.LIGHT_GRAY5,
  buttonBackground: Colors.LIGHT_GRAY1,
  gridSelectedBackground: '#83b7eb',
  gridSelectedShadow: '#868e96',
  playingRowBackground: Colors.GREEN3,
  windowControlsColor: '#909d9e',
  songTimeColor: '#36494d',
  visualizerColor: '#0234a1',
  volumeSliderColor: Colors.DARK_GRAY4,
  songProgressColor1: Colors.BLUE5,
  songProgressColor2: Colors.BLUE5,
  omnibarBackground: Colors.WHITE,
  suggestedTagColors: [
    '#137CBD',
    '#4580E6',
    '#29A634',
    '#D99E0B',
    '#0F9960',
    '#AD99FF',
    '#728C23',
    '#D9822B',
    '#DB3737',
    '#DB2C6F',
    '#96622D',
    '#008075',
    '#D13913',
    '#C274C2',
  ],
};
