[package]
authors = ["aschey <aschey13@gmail.com>"]
edition = "2018"
name = "platuned"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
flexi_logger = "0.18.0"
futures = "0.3.16"
libplatune-management = {path = "../../libplatune/management"}
libplatune-player = {path = "../../libplatune/player"}
log = "0.4.14"
prost = "0.8.0"
tokio = {version = "1.10.0", features = ["full"]}
tokio-stream = {version = "0.1.7", features = ["net"]}
tonic = "0.5.2"
tonic-reflection = "0.2.0"
yansi = "0.5.0"

[build-dependencies]
tonic-build = {version = "0.5.2", features = ["prost"]}
