[package]
authors = ["aschey <aschey13@gmail.com>"]
edition = "2024"
name = "platuned"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
axum = { version = "0.8.1", optional = true }
clap = { version = "4.5.26", features = ["unstable-styles"] }
console-subscriber = { version = "0.4.1", features = [
  "parking_lot",
], optional = true }
daemon-slayer = { git = "https://github.com/aschey/daemon-slayer", rev = "1d45e3318cf3b11b8970d741b1a501243021d9ef", features = [
  "client-standard",
  "server-standard",
  "notify",
  "grpc-health-check",
  "logging-ipc",
  "native-notification",
  "build-info",
] }
directories = "6.0.0"
dotenvy = "0.15.7"
futures = "0.3.31"
libplatune-management = { path = "../../libplatune/management", optional = true }
libplatune-player = { path = "../../libplatune/player", optional = true }
tipsy = "0.3.1"
prost = "0.13.4"
prost-types = "0.13.4"
rcgen = { version = "0.13.2", features = ["x509-parser", "pem"] }
time = "0.3.37"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
tonic = { version = "0.12.3", features = ["tls"] }
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"
tower = { version = "0.5.2", optional = true }
tower-http = { version = "0.6.2", features = ["fs"], optional = true }
tracing = "0.1.41"
uuid = { version = "1.11.1", features = ["v4"] }
vergen-gix = { version = "1.0.6" }
console = "0.15.10"
which = { version = "7.0.1", features = ["tracing"] }

[features]
default = ["management", "player"]
management = ["libplatune-management", "tower", "tower-http", "axum"]
player = ["libplatune-player"]
tokio-console = ["console-subscriber", "tokio/tracing"]

[build-dependencies]
tonic-build = { version = "0.12.3", features = ["prost"] }
vergen-gix = { version = "1.0.6", features = ["build", "cargo", "rustc", "si"] }
