[package]
authors = ["aschey <aschey13@gmail.com>"]
edition = "2021"
name = "platuned"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.79"
axum = { version = "0.7.5", optional = true }
clap = { version = "4.5.4", features = ["unstable-styles"] }
console-subscriber = { version = "0.2.0", features = [
    "parking_lot",
], optional = true }
daemon-slayer = { git = "https://github.com/aschey/daemon-slayer", rev = "23659b534dbb46eb4d9b7d251037a9a67a6ce50e", features = [
    "client-standard",
    "server-standard",
    "notify",
    "grpc-health-check",
    "logging-ipc",
    "native-notification",
    "build-info",
] }
dotenvy = "0.15.7"
futures = "0.3.30"
libplatune-management = { path = "../../libplatune/management", optional = true }
libplatune-player = { path = "../../libplatune/player", optional = true }
parity-tokio-ipc = { git = "https://github.com/aschey/parity-tokio-ipc", rev = "588198a0abb32a79f6f3e656ff0472008e4ba9b8" }
prost = "0.12.3"
prost-types = "0.12.3"
rcgen = { version = "0.13.0", features = ["x509-parser"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
tonic = { version = "0.11.0", features = ["tls"] }
tonic-health = "0.11.0"
tonic-reflection = "0.11.0"
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.5.2", features = ["fs"], optional = true }
tracing = "0.1.40"
uuid = { version = "1.8.0", features = ["v4"] }

[features]
default = ["management", "player"]
management = ["libplatune-management", "tower", "tower-http", "axum"]
player = ["libplatune-player"]
tokio-console = ["console-subscriber", "tokio/tracing"]

[build-dependencies]
tonic-build = { version = "0.11.0", features = ["prost"] }
daemon-slayer = { git = "https://github.com/aschey/daemon-slayer", rev = "23659b534dbb46eb4d9b7d251037a9a67a6ce50e", features = [
    "build-info",
    "build-info-build",
    "build-info-cargo",
    "build-info-git",
    "build-info-rustc",
    "build-info-si",
] }
