[package]
authors = ["aschey <aschey13@gmail.com>"]
edition = "2021"
name = "platuned"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.73"
clap = { version = "4.3.21", features = ["unstable-styles"] }
console-subscriber = { version = "0.1.10", features = [
    "parking_lot",
], optional = true }
daemon-slayer = { git = "https://github.com/aschey/daemon-slayer", rev = "29211232215525fe6d898ebaafae167b777879cc", features = [
    "client-standard",
    "server-standard",
    "notify",
    "grpc-health-check",
    "logging-ipc",
    "native-notification",
    "build-info",
] }
dotenvy = "0.15.7"
futures = "0.3.28"
hyper = { version = "0.14.27", optional = true }
libplatune-management = { path = "../../libplatune/management", optional = true }
libplatune-player = { path = "../../libplatune/player", optional = true }
parity-tokio-ipc = "0.9.0"
prost = "0.11.9"
prost-types = "0.11.9"
rcgen = { version = "0.11.1", features = ["x509-parser"] }
tokio = { version = "1.31.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
tonic = { version = "0.9.2", features = ["tls"] }
tonic-health = "0.9.2"
tonic-reflection = "0.9.2"
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4.3", features = ["fs"], optional = true }
tracing = "0.1.37"
uuid = { version = "1.4.1", features = ["v4"] }

[features]
default = ["management", "player"]
management = ["libplatune-management", "tower", "tower-http", "hyper"]
player = ["libplatune-player"]
tokio-console = ["console-subscriber", "tokio/tracing"]

[build-dependencies]
tonic-build = { version = "0.9.2", features = ["prost"] }
daemon-slayer = { git = "https://github.com/aschey/daemon-slayer", rev = "29211232215525fe6d898ebaafae167b777879cc", features = [
    "build-info",
    "build-info-build",
    "build-info-cargo",
    "build-info-git",
    "build-info-rustc",
    "build-info-si",
] }
