[package]
authors = ["aschey <aschey13@gmail.com>"]
edition = "2021"
name = "platuned"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.66"
console-subscriber = {version = "0.1.8", features = ["parking_lot"], optional = true}
daemon-slayer = {git = "https://github.com/aschey/daemon-slayer", rev = "c41388f965abb78df0fe68b06e9e1f6000bf425b", features = ["client-standard", "server-standard", "grpc-health-check"]}
dotenvy = "0.15.6"
futures = "0.3.26"
hyper = {version = "0.14.25", optional = true}
libplatune-management = {path = "../../libplatune/management", optional = true}
libplatune-player = {path = "../../libplatune/player", optional = true}
parity-tokio-ipc = "0.9.0"
prost = "0.11.8"
prost-types = "0.11.8"
rcgen = {version = "0.10.0", features = ["x509-parser"]}
tokio = {version = "1.26.0", features = ["rt-multi-thread", "macros"]}
tokio-stream = {version = "0.1.12", features = ["net"]}
tonic = {version = "0.8.3", features = ["tls"]}
tonic-health = "0.8.0"
tonic-reflection = "0.6.0"
tower = {version = "0.4.13", optional = true}
tower-http = {version = "0.4.0", features = ["fs"], optional = true}
tracing = "0.1.37"
uuid = {version = "1.3.0", features = ["v4"]}

[features]
default = ["management", "player"]
management = ["libplatune-management", "tower", "tower-http", "hyper"]
player = ["libplatune-player"]
tokio-console = ["console-subscriber", "tokio/tracing"]
[build-dependencies]
tonic-build = {version = "0.8.4", features = ["prost"]}
