// source: player.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.platune.player.v1.DevicesResponse', null, global);
goog.exportSymbol('proto.platune.player.v1.Event', null, global);
goog.exportSymbol('proto.platune.player.v1.EventResponse', null, global);
goog.exportSymbol('proto.platune.player.v1.EventResponse.EventPayloadCase', null, global);
goog.exportSymbol('proto.platune.player.v1.Metadata', null, global);
goog.exportSymbol('proto.platune.player.v1.PlayerStatus', null, global);
goog.exportSymbol('proto.platune.player.v1.PositionResponse', null, global);
goog.exportSymbol('proto.platune.player.v1.QueueRequest', null, global);
goog.exportSymbol('proto.platune.player.v1.SeekMode', null, global);
goog.exportSymbol('proto.platune.player.v1.SeekRequest', null, global);
goog.exportSymbol('proto.platune.player.v1.SeekResponse', null, global);
goog.exportSymbol('proto.platune.player.v1.SetOutputDeviceRequest', null, global);
goog.exportSymbol('proto.platune.player.v1.SetVolumeRequest', null, global);
goog.exportSymbol('proto.platune.player.v1.State', null, global);
goog.exportSymbol('proto.platune.player.v1.StatusResponse', null, global);
goog.exportSymbol('proto.platune.player.v1.Track', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.Track = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.Track, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.Track.displayName = 'proto.platune.player.v1.Track';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.QueueRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.platune.player.v1.QueueRequest.repeatedFields_, null);
};
goog.inherits(proto.platune.player.v1.QueueRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.QueueRequest.displayName = 'proto.platune.player.v1.QueueRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.SeekRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.SeekRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.SeekRequest.displayName = 'proto.platune.player.v1.SeekRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.SetVolumeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.SetVolumeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.SetVolumeRequest.displayName = 'proto.platune.player.v1.SetVolumeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.EventResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.platune.player.v1.EventResponse.oneofGroups_);
};
goog.inherits(proto.platune.player.v1.EventResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.EventResponse.displayName = 'proto.platune.player.v1.EventResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.Metadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.Metadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.Metadata.displayName = 'proto.platune.player.v1.Metadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.State = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.platune.player.v1.State.repeatedFields_, null);
};
goog.inherits(proto.platune.player.v1.State, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.State.displayName = 'proto.platune.player.v1.State';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.PositionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.PositionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.PositionResponse.displayName = 'proto.platune.player.v1.PositionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.SeekResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.SeekResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.SeekResponse.displayName = 'proto.platune.player.v1.SeekResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.StatusResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.StatusResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.StatusResponse.displayName = 'proto.platune.player.v1.StatusResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.DevicesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.platune.player.v1.DevicesResponse.repeatedFields_, null);
};
goog.inherits(proto.platune.player.v1.DevicesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.DevicesResponse.displayName = 'proto.platune.player.v1.DevicesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.platune.player.v1.SetOutputDeviceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.platune.player.v1.SetOutputDeviceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.platune.player.v1.SetOutputDeviceRequest.displayName = 'proto.platune.player.v1.SetOutputDeviceRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.Track.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.Track.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.Track} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.Track.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    metadata: (f = msg.getMetadata()) && proto.platune.player.v1.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.Track}
 */
proto.platune.player.v1.Track.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.Track;
  return proto.platune.player.v1.Track.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.Track} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.Track}
 */
proto.platune.player.v1.Track.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = new proto.platune.player.v1.Metadata;
      reader.readMessage(value,proto.platune.player.v1.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.Track.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.Track.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.Track} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.Track.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.platune.player.v1.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.platune.player.v1.Track.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.platune.player.v1.Track} returns this
 */
proto.platune.player.v1.Track.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Metadata metadata = 2;
 * @return {?proto.platune.player.v1.Metadata}
 */
proto.platune.player.v1.Track.prototype.getMetadata = function() {
  return /** @type{?proto.platune.player.v1.Metadata} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.Metadata, 2));
};


/**
 * @param {?proto.platune.player.v1.Metadata|undefined} value
 * @return {!proto.platune.player.v1.Track} returns this
*/
proto.platune.player.v1.Track.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.Track} returns this
 */
proto.platune.player.v1.Track.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Track.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.platune.player.v1.QueueRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.QueueRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.QueueRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.QueueRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.QueueRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    queueList: jspb.Message.toObjectList(msg.getQueueList(),
    proto.platune.player.v1.Track.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.QueueRequest}
 */
proto.platune.player.v1.QueueRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.QueueRequest;
  return proto.platune.player.v1.QueueRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.QueueRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.QueueRequest}
 */
proto.platune.player.v1.QueueRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.platune.player.v1.Track;
      reader.readMessage(value,proto.platune.player.v1.Track.deserializeBinaryFromReader);
      msg.addQueue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.QueueRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.QueueRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.QueueRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.QueueRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQueueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.platune.player.v1.Track.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Track queue = 1;
 * @return {!Array<!proto.platune.player.v1.Track>}
 */
proto.platune.player.v1.QueueRequest.prototype.getQueueList = function() {
  return /** @type{!Array<!proto.platune.player.v1.Track>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.platune.player.v1.Track, 1));
};


/**
 * @param {!Array<!proto.platune.player.v1.Track>} value
 * @return {!proto.platune.player.v1.QueueRequest} returns this
*/
proto.platune.player.v1.QueueRequest.prototype.setQueueList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.platune.player.v1.Track=} opt_value
 * @param {number=} opt_index
 * @return {!proto.platune.player.v1.Track}
 */
proto.platune.player.v1.QueueRequest.prototype.addQueue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.platune.player.v1.Track, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.platune.player.v1.QueueRequest} returns this
 */
proto.platune.player.v1.QueueRequest.prototype.clearQueueList = function() {
  return this.setQueueList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.SeekRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.SeekRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.SeekRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SeekRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    time: (f = msg.getTime()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    mode: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.SeekRequest}
 */
proto.platune.player.v1.SeekRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.SeekRequest;
  return proto.platune.player.v1.SeekRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.SeekRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.SeekRequest}
 */
proto.platune.player.v1.SeekRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 2:
      var value = /** @type {!proto.platune.player.v1.SeekMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.SeekRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.SeekRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.SeekRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SeekRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional google.protobuf.Duration time = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.platune.player.v1.SeekRequest.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.platune.player.v1.SeekRequest} returns this
*/
proto.platune.player.v1.SeekRequest.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.SeekRequest} returns this
 */
proto.platune.player.v1.SeekRequest.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.SeekRequest.prototype.hasTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SeekMode mode = 2;
 * @return {!proto.platune.player.v1.SeekMode}
 */
proto.platune.player.v1.SeekRequest.prototype.getMode = function() {
  return /** @type {!proto.platune.player.v1.SeekMode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.platune.player.v1.SeekMode} value
 * @return {!proto.platune.player.v1.SeekRequest} returns this
 */
proto.platune.player.v1.SeekRequest.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.SetVolumeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.SetVolumeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.SetVolumeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SetVolumeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    volume: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.SetVolumeRequest}
 */
proto.platune.player.v1.SetVolumeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.SetVolumeRequest;
  return proto.platune.player.v1.SetVolumeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.SetVolumeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.SetVolumeRequest}
 */
proto.platune.player.v1.SetVolumeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setVolume(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.SetVolumeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.SetVolumeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.SetVolumeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SetVolumeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVolume();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
};


/**
 * optional float volume = 1;
 * @return {number}
 */
proto.platune.player.v1.SetVolumeRequest.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.platune.player.v1.SetVolumeRequest} returns this
 */
proto.platune.player.v1.SetVolumeRequest.prototype.setVolume = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.platune.player.v1.EventResponse.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.platune.player.v1.EventResponse.EventPayloadCase = {
  EVENT_PAYLOAD_NOT_SET: 0,
  STATE: 2,
  SEEK_DATA: 3,
  PROGRESS: 4
};

/**
 * @return {proto.platune.player.v1.EventResponse.EventPayloadCase}
 */
proto.platune.player.v1.EventResponse.prototype.getEventPayloadCase = function() {
  return /** @type {proto.platune.player.v1.EventResponse.EventPayloadCase} */(jspb.Message.computeOneofCase(this, proto.platune.player.v1.EventResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.EventResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.EventResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.EventResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.EventResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    event: jspb.Message.getFieldWithDefault(msg, 1, 0),
    state: (f = msg.getState()) && proto.platune.player.v1.State.toObject(includeInstance, f),
    seekData: (f = msg.getSeekData()) && proto.platune.player.v1.SeekResponse.toObject(includeInstance, f),
    progress: (f = msg.getProgress()) && proto.platune.player.v1.PositionResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.EventResponse}
 */
proto.platune.player.v1.EventResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.EventResponse;
  return proto.platune.player.v1.EventResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.EventResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.EventResponse}
 */
proto.platune.player.v1.EventResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.platune.player.v1.Event} */ (reader.readEnum());
      msg.setEvent(value);
      break;
    case 2:
      var value = new proto.platune.player.v1.State;
      reader.readMessage(value,proto.platune.player.v1.State.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    case 3:
      var value = new proto.platune.player.v1.SeekResponse;
      reader.readMessage(value,proto.platune.player.v1.SeekResponse.deserializeBinaryFromReader);
      msg.setSeekData(value);
      break;
    case 4:
      var value = new proto.platune.player.v1.PositionResponse;
      reader.readMessage(value,proto.platune.player.v1.PositionResponse.deserializeBinaryFromReader);
      msg.setProgress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.EventResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.EventResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.EventResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.EventResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvent();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.platune.player.v1.State.serializeBinaryToWriter
    );
  }
  f = message.getSeekData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.platune.player.v1.SeekResponse.serializeBinaryToWriter
    );
  }
  f = message.getProgress();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.platune.player.v1.PositionResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional Event event = 1;
 * @return {!proto.platune.player.v1.Event}
 */
proto.platune.player.v1.EventResponse.prototype.getEvent = function() {
  return /** @type {!proto.platune.player.v1.Event} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.platune.player.v1.Event} value
 * @return {!proto.platune.player.v1.EventResponse} returns this
 */
proto.platune.player.v1.EventResponse.prototype.setEvent = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional State state = 2;
 * @return {?proto.platune.player.v1.State}
 */
proto.platune.player.v1.EventResponse.prototype.getState = function() {
  return /** @type{?proto.platune.player.v1.State} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.State, 2));
};


/**
 * @param {?proto.platune.player.v1.State|undefined} value
 * @return {!proto.platune.player.v1.EventResponse} returns this
*/
proto.platune.player.v1.EventResponse.prototype.setState = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.platune.player.v1.EventResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.EventResponse} returns this
 */
proto.platune.player.v1.EventResponse.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.EventResponse.prototype.hasState = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SeekResponse seek_data = 3;
 * @return {?proto.platune.player.v1.SeekResponse}
 */
proto.platune.player.v1.EventResponse.prototype.getSeekData = function() {
  return /** @type{?proto.platune.player.v1.SeekResponse} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.SeekResponse, 3));
};


/**
 * @param {?proto.platune.player.v1.SeekResponse|undefined} value
 * @return {!proto.platune.player.v1.EventResponse} returns this
*/
proto.platune.player.v1.EventResponse.prototype.setSeekData = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.platune.player.v1.EventResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.EventResponse} returns this
 */
proto.platune.player.v1.EventResponse.prototype.clearSeekData = function() {
  return this.setSeekData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.EventResponse.prototype.hasSeekData = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PositionResponse progress = 4;
 * @return {?proto.platune.player.v1.PositionResponse}
 */
proto.platune.player.v1.EventResponse.prototype.getProgress = function() {
  return /** @type{?proto.platune.player.v1.PositionResponse} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.PositionResponse, 4));
};


/**
 * @param {?proto.platune.player.v1.PositionResponse|undefined} value
 * @return {!proto.platune.player.v1.EventResponse} returns this
*/
proto.platune.player.v1.EventResponse.prototype.setProgress = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.platune.player.v1.EventResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.EventResponse} returns this
 */
proto.platune.player.v1.EventResponse.prototype.clearProgress = function() {
  return this.setProgress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.EventResponse.prototype.hasProgress = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.Metadata.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.Metadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.Metadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.Metadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    artist: jspb.Message.getFieldWithDefault(msg, 1, ""),
    albumArtist: jspb.Message.getFieldWithDefault(msg, 2, ""),
    album: jspb.Message.getFieldWithDefault(msg, 3, ""),
    song: jspb.Message.getFieldWithDefault(msg, 4, ""),
    trackNumber: jspb.Message.getFieldWithDefault(msg, 5, 0),
    duration: (f = msg.getDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.Metadata}
 */
proto.platune.player.v1.Metadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.Metadata;
  return proto.platune.player.v1.Metadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.Metadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.Metadata}
 */
proto.platune.player.v1.Metadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setArtist(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlbumArtist(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlbum(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSong(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTrackNumber(value);
      break;
    case 6:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.Metadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.Metadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.Metadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.Metadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional string artist = 1;
 * @return {string}
 */
proto.platune.player.v1.Metadata.prototype.getArtist = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.setArtist = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.clearArtist = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Metadata.prototype.hasArtist = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string album_artist = 2;
 * @return {string}
 */
proto.platune.player.v1.Metadata.prototype.getAlbumArtist = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.setAlbumArtist = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.clearAlbumArtist = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Metadata.prototype.hasAlbumArtist = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string album = 3;
 * @return {string}
 */
proto.platune.player.v1.Metadata.prototype.getAlbum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.setAlbum = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.clearAlbum = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Metadata.prototype.hasAlbum = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string song = 4;
 * @return {string}
 */
proto.platune.player.v1.Metadata.prototype.getSong = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.setSong = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.clearSong = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Metadata.prototype.hasSong = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int64 track_number = 5;
 * @return {number}
 */
proto.platune.player.v1.Metadata.prototype.getTrackNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.setTrackNumber = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.clearTrackNumber = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Metadata.prototype.hasTrackNumber = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Duration duration = 6;
 * @return {?proto.google.protobuf.Duration}
 */
proto.platune.player.v1.Metadata.prototype.getDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 6));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.platune.player.v1.Metadata} returns this
*/
proto.platune.player.v1.Metadata.prototype.setDuration = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.Metadata} returns this
 */
proto.platune.player.v1.Metadata.prototype.clearDuration = function() {
  return this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.Metadata.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.platune.player.v1.State.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.State.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.State.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.State} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.State.toObject = function(includeInstance, msg) {
  var f, obj = {
    queueList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    queuePosition: jspb.Message.getFieldWithDefault(msg, 2, 0),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    volume: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    metadata: (f = msg.getMetadata()) && proto.platune.player.v1.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.State}
 */
proto.platune.player.v1.State.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.State;
  return proto.platune.player.v1.State.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.State} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.State}
 */
proto.platune.player.v1.State.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addQueue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setQueuePosition(value);
      break;
    case 3:
      var value = /** @type {!proto.platune.player.v1.PlayerStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setVolume(value);
      break;
    case 5:
      var value = new proto.platune.player.v1.Metadata;
      reader.readMessage(value,proto.platune.player.v1.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.State.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.State.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.State} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.State.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQueueList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getQueuePosition();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.platune.player.v1.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string queue = 1;
 * @return {!Array<string>}
 */
proto.platune.player.v1.State.prototype.getQueueList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.setQueueList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.addQueue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.clearQueueList = function() {
  return this.setQueueList([]);
};


/**
 * optional uint32 queue_position = 2;
 * @return {number}
 */
proto.platune.player.v1.State.prototype.getQueuePosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.setQueuePosition = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional PlayerStatus status = 3;
 * @return {!proto.platune.player.v1.PlayerStatus}
 */
proto.platune.player.v1.State.prototype.getStatus = function() {
  return /** @type {!proto.platune.player.v1.PlayerStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.platune.player.v1.PlayerStatus} value
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional float volume = 4;
 * @return {number}
 */
proto.platune.player.v1.State.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.setVolume = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional Metadata metadata = 5;
 * @return {?proto.platune.player.v1.Metadata}
 */
proto.platune.player.v1.State.prototype.getMetadata = function() {
  return /** @type{?proto.platune.player.v1.Metadata} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.Metadata, 5));
};


/**
 * @param {?proto.platune.player.v1.Metadata|undefined} value
 * @return {!proto.platune.player.v1.State} returns this
*/
proto.platune.player.v1.State.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.State} returns this
 */
proto.platune.player.v1.State.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.State.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.PositionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.PositionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.PositionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.PositionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    position: (f = msg.getPosition()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    retrievalTime: (f = msg.getRetrievalTime()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.PositionResponse}
 */
proto.platune.player.v1.PositionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.PositionResponse;
  return proto.platune.player.v1.PositionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.PositionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.PositionResponse}
 */
proto.platune.player.v1.PositionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 2:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRetrievalTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.PositionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.PositionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.PositionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.PositionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getRetrievalTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Duration position = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.platune.player.v1.PositionResponse.prototype.getPosition = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.platune.player.v1.PositionResponse} returns this
*/
proto.platune.player.v1.PositionResponse.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.PositionResponse} returns this
 */
proto.platune.player.v1.PositionResponse.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.PositionResponse.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Duration retrieval_time = 2;
 * @return {?proto.google.protobuf.Duration}
 */
proto.platune.player.v1.PositionResponse.prototype.getRetrievalTime = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 2));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.platune.player.v1.PositionResponse} returns this
*/
proto.platune.player.v1.PositionResponse.prototype.setRetrievalTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.PositionResponse} returns this
 */
proto.platune.player.v1.PositionResponse.prototype.clearRetrievalTime = function() {
  return this.setRetrievalTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.PositionResponse.prototype.hasRetrievalTime = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.SeekResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.SeekResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.SeekResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SeekResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    state: (f = msg.getState()) && proto.platune.player.v1.State.toObject(includeInstance, f),
    seekMillis: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.SeekResponse}
 */
proto.platune.player.v1.SeekResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.SeekResponse;
  return proto.platune.player.v1.SeekResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.SeekResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.SeekResponse}
 */
proto.platune.player.v1.SeekResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.platune.player.v1.State;
      reader.readMessage(value,proto.platune.player.v1.State.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSeekMillis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.SeekResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.SeekResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.SeekResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SeekResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.platune.player.v1.State.serializeBinaryToWriter
    );
  }
  f = message.getSeekMillis();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * optional State state = 1;
 * @return {?proto.platune.player.v1.State}
 */
proto.platune.player.v1.SeekResponse.prototype.getState = function() {
  return /** @type{?proto.platune.player.v1.State} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.State, 1));
};


/**
 * @param {?proto.platune.player.v1.State|undefined} value
 * @return {!proto.platune.player.v1.SeekResponse} returns this
*/
proto.platune.player.v1.SeekResponse.prototype.setState = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.SeekResponse} returns this
 */
proto.platune.player.v1.SeekResponse.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.SeekResponse.prototype.hasState = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 seek_millis = 2;
 * @return {number}
 */
proto.platune.player.v1.SeekResponse.prototype.getSeekMillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.platune.player.v1.SeekResponse} returns this
 */
proto.platune.player.v1.SeekResponse.prototype.setSeekMillis = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.StatusResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.StatusResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.StatusResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.StatusResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    state: (f = msg.getState()) && proto.platune.player.v1.State.toObject(includeInstance, f),
    progress: (f = msg.getProgress()) && proto.platune.player.v1.PositionResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.StatusResponse}
 */
proto.platune.player.v1.StatusResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.StatusResponse;
  return proto.platune.player.v1.StatusResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.StatusResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.StatusResponse}
 */
proto.platune.player.v1.StatusResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.platune.player.v1.State;
      reader.readMessage(value,proto.platune.player.v1.State.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    case 2:
      var value = new proto.platune.player.v1.PositionResponse;
      reader.readMessage(value,proto.platune.player.v1.PositionResponse.deserializeBinaryFromReader);
      msg.setProgress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.StatusResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.StatusResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.StatusResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.StatusResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.platune.player.v1.State.serializeBinaryToWriter
    );
  }
  f = message.getProgress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.platune.player.v1.PositionResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional State state = 1;
 * @return {?proto.platune.player.v1.State}
 */
proto.platune.player.v1.StatusResponse.prototype.getState = function() {
  return /** @type{?proto.platune.player.v1.State} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.State, 1));
};


/**
 * @param {?proto.platune.player.v1.State|undefined} value
 * @return {!proto.platune.player.v1.StatusResponse} returns this
*/
proto.platune.player.v1.StatusResponse.prototype.setState = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.StatusResponse} returns this
 */
proto.platune.player.v1.StatusResponse.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.StatusResponse.prototype.hasState = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PositionResponse progress = 2;
 * @return {?proto.platune.player.v1.PositionResponse}
 */
proto.platune.player.v1.StatusResponse.prototype.getProgress = function() {
  return /** @type{?proto.platune.player.v1.PositionResponse} */ (
    jspb.Message.getWrapperField(this, proto.platune.player.v1.PositionResponse, 2));
};


/**
 * @param {?proto.platune.player.v1.PositionResponse|undefined} value
 * @return {!proto.platune.player.v1.StatusResponse} returns this
*/
proto.platune.player.v1.StatusResponse.prototype.setProgress = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.platune.player.v1.StatusResponse} returns this
 */
proto.platune.player.v1.StatusResponse.prototype.clearProgress = function() {
  return this.setProgress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.StatusResponse.prototype.hasProgress = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.platune.player.v1.DevicesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.DevicesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.DevicesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.DevicesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.DevicesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    devicesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.DevicesResponse}
 */
proto.platune.player.v1.DevicesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.DevicesResponse;
  return proto.platune.player.v1.DevicesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.DevicesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.DevicesResponse}
 */
proto.platune.player.v1.DevicesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addDevices(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.DevicesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.DevicesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.DevicesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.DevicesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevicesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string devices = 1;
 * @return {!Array<string>}
 */
proto.platune.player.v1.DevicesResponse.prototype.getDevicesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.platune.player.v1.DevicesResponse} returns this
 */
proto.platune.player.v1.DevicesResponse.prototype.setDevicesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.platune.player.v1.DevicesResponse} returns this
 */
proto.platune.player.v1.DevicesResponse.prototype.addDevices = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.platune.player.v1.DevicesResponse} returns this
 */
proto.platune.player.v1.DevicesResponse.prototype.clearDevicesList = function() {
  return this.setDevicesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.platune.player.v1.SetOutputDeviceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.platune.player.v1.SetOutputDeviceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.platune.player.v1.SetOutputDeviceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SetOutputDeviceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    device: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.platune.player.v1.SetOutputDeviceRequest}
 */
proto.platune.player.v1.SetOutputDeviceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.platune.player.v1.SetOutputDeviceRequest;
  return proto.platune.player.v1.SetOutputDeviceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.platune.player.v1.SetOutputDeviceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.platune.player.v1.SetOutputDeviceRequest}
 */
proto.platune.player.v1.SetOutputDeviceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.platune.player.v1.SetOutputDeviceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.platune.player.v1.SetOutputDeviceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.platune.player.v1.SetOutputDeviceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.platune.player.v1.SetOutputDeviceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string device = 1;
 * @return {string}
 */
proto.platune.player.v1.SetOutputDeviceRequest.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.platune.player.v1.SetOutputDeviceRequest} returns this
 */
proto.platune.player.v1.SetOutputDeviceRequest.prototype.setDevice = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.platune.player.v1.SetOutputDeviceRequest} returns this
 */
proto.platune.player.v1.SetOutputDeviceRequest.prototype.clearDevice = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.platune.player.v1.SetOutputDeviceRequest.prototype.hasDevice = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * @enum {number}
 */
proto.platune.player.v1.Event = {
  START_QUEUE: 0,
  QUEUE_UPDATED: 1,
  STOP: 2,
  PAUSE: 3,
  RESUME: 4,
  TRACK_CHANGED: 5,
  SET_VOLUME: 6,
  SEEK: 7,
  QUEUE_ENDED: 8,
  POSITION: 9
};

/**
 * @enum {number}
 */
proto.platune.player.v1.PlayerStatus = {
  PLAYING: 0,
  STOPPED: 1,
  PAUSED: 2
};

/**
 * @enum {number}
 */
proto.platune.player.v1.SeekMode = {
  FORWARD: 0,
  BACKWARD: 1,
  ABSOLUTE: 2
};

goog.object.extend(exports, proto.platune.player.v1);
