#!/usr/bin/env bash
CURRENT_DIR=$(dirname $0)
mockgen -package=test -source="${CURRENT_DIR}/../platuned/client/go/player_rpc_grpc.pb.go" > "${CURRENT_DIR}/test/player_mock.go"
mockgen -package=test -source="${CURRENT_DIR}/../platuned/client/go/management_rpc_grpc.pb.go" > "${CURRENT_DIR}/test/management_mock.go"
# autogenerated package is slightly wrong, need to remove v2 at the end
sed -i 's_client/v2_client_g' "${CURRENT_DIR}/test/player_mock.go"
sed -i 's_client/v2_client_g' "${CURRENT_DIR}/test/management_mock.go"

echo "regenerated mocks"