#!/usr/bin/env sh

relative_dir="$(dirname "$0")/.."
repo_dir="$(realpath "$relative_dir")"

cd "${repo_dir}/platuned/server"
cargo build --release
platunectl stop
pkill 'platune-tray'
cd "${repo_dir}/platune-tray"
cargo packager --release

cp "${repo_dir}/target/release/platuned" "${LOCAL_BIN}/" 
cp "${repo_dir}/target/release/platunectl" "${LOCAL_BIN}/"
cd "${repo_dir}/platune-cli"

go build .
cp ./cli "${LOCAL_BIN}/platune-cli"

platunectl start
platunectl tray enable
open -n '/Applications/Platune Tray.app'
