#!/usr/bin/env sh
source $(dirname $0)/.env

read -p "Are you sure you want to overwrite the contents of the Windows VM with the local contents? [yn] " -n 1 -r
[[ ! $REPLY =~ ^[Yy]$ ]] && exit 1
echo
sshpass -p "${QUICKEMU_WINDOWS_PASSWORD}" ssh -p 22220 Quickemu@localhost << EOF
if not exist "C:\Users\Quickemu\daemon-slayer" (
    mkdir "C:\Users\Quickemu\daemon-slayer"
)
EOF
echo
rsync -arv -e "sshpass -p ${QUICKEMU_WINDOWS_PASSWORD} ssh -p 22220" --delete --progress --exclude target --exclude .git --exclude .env ./ Quickemu@localhost:/c/Users/${QUICKEMU_WINDOWS_USERNAME:-Quickemu}/platune
