#!/usr/bin/env sh
source $(dirname $0)/.env

read -p "Are you sure you want to overwrite the contents of the Mac VM with the local contents? [yn] " -n 1 -r
[[ ! $REPLY =~ ^[Yy]$ ]] && exit 1
echo
sshpass -p "${QUICKEMU_MAC_PASSWORD}" ssh -p 22221 "${QUICKEMU_MAC_USERNAME}@localhost" << EOF
mkdir -p ~/daemon-slayer
EOF
echo
rsync -arv -e "sshpass -p ${QUICKEMU_MAC_PASSWORD} ssh -p 22221" --delete --progress --exclude target --exclude .git ./ "${QUICKEMU_MAC_USERNAME}@localhost:/Users/${QUICKEMU_MAC_USERNAME}/platune"
