# remove -s none when this is resolved https://github.com/rust-fuzz/cargo-fuzz/issues/404
[tasks.fuzz]
args = [
    "+nightly",
    "fuzz",
    "run",
    "player",
    "-s",
    "none",
    "--target",
    "x86_64-unknown-linux-gnu",
    "--",
    "-detect_leaks=0",
]
workspace = false
command = "cargo"
condition = { platforms = ["linux"] }
install_crate = "cargo-fuzz"

[tasks.update]
workspace = false
args = ["update"]
command = "cargo"
install_crate = "cargo-add"

[tasks.upgrade]
workspace = false
args = ["upgrade"]
command = "cargo"
install_crate = "cargo-add"

[tasks.update-all]
workspace = false
dependencies = ["update", "upgrade"]
