[tasks.fuzz]
args = [
    "+nightly",
    "fuzz",
    "run",
    "player",
    "--target",
    "x86_64-unknown-linux-gnu",
    "--",
    "-detect_leaks=0",
]
command = "cargo"
condition = { platforms = ["linux"] }
install_crate = "cargo-fuzz"

[tasks.update]
args = ["update"]
command = "cargo"
install_crate = "cargo-add"

[tasks.upgrade]
args = ["upgrade"]
command = "cargo"
install_crate = "cargo-add"

[tasks.update-all]
dependencies = ["update", "upgrade"]
