[tasks.fuzz]
args = ["fuzz", "run", "player", "--", "-detect_leaks=0"]
command = "cargo"
condition = {platforms = ["linux"]}
install_crate = "cargo-fuzz"

[tasks.update]
args = ["update"]
command = "cargo"
install_crate = "cargo-add"

[tasks.upgrade]
args = ["upgrade"]
command = "cargo"
install_crate = "cargo-add"

[tasks.update-all]
dependencies = ["update", "upgrade"]
