// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package folder

import (
	"github.com/aschey/platune/cli/internal"
)

// Injectors from wire.go:

func InitializeFolderCommand(playerClient *internal.PlayerClient, managementClient *internal.ManagementClient) FolderCmd {
	folderAddFolderCmd := newAddFolderCmd(managementClient)
	folderListFoldersCmd := newListFoldersCmd(managementClient)
	folderCommands := commands{
		add:  folderAddFolderCmd,
		list: folderListFoldersCmd,
	}
	folderCmd := newFolderCmd(folderCommands)
	return folderCmd
}

// wire.go:

type commands struct {
	add  addFolderCmd
	list listFoldersCmd
}
