// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: player.proto

package player_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_START_QUEUE   Event = 0
	Event_QUEUE_UPDATED Event = 1
	Event_STOP          Event = 2
	Event_PAUSE         Event = 3
	Event_RESUME        Event = 4
	Event_TRACK_CHANGED Event = 5
	Event_SET_VOLUME    Event = 6
	Event_SEEK          Event = 7
	Event_QUEUE_ENDED   Event = 8
	Event_POSITION      Event = 9
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "START_QUEUE",
		1: "QUEUE_UPDATED",
		2: "STOP",
		3: "PAUSE",
		4: "RESUME",
		5: "TRACK_CHANGED",
		6: "SET_VOLUME",
		7: "SEEK",
		8: "QUEUE_ENDED",
		9: "POSITION",
	}
	Event_value = map[string]int32{
		"START_QUEUE":   0,
		"QUEUE_UPDATED": 1,
		"STOP":          2,
		"PAUSE":         3,
		"RESUME":        4,
		"TRACK_CHANGED": 5,
		"SET_VOLUME":    6,
		"SEEK":          7,
		"QUEUE_ENDED":   8,
		"POSITION":      9,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_player_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_player_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

type PlayerStatus int32

const (
	PlayerStatus_PLAYING PlayerStatus = 0
	PlayerStatus_STOPPED PlayerStatus = 1
	PlayerStatus_PAUSED  PlayerStatus = 2
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYING",
		1: "STOPPED",
		2: "PAUSED",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYING": 0,
		"STOPPED": 1,
		"PAUSED":  2,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_player_proto_enumTypes[1].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_player_proto_enumTypes[1]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

type SeekMode int32

const (
	SeekMode_FORWARD  SeekMode = 0
	SeekMode_BACKWARD SeekMode = 1
	SeekMode_ABSOLUTE SeekMode = 2
)

// Enum value maps for SeekMode.
var (
	SeekMode_name = map[int32]string{
		0: "FORWARD",
		1: "BACKWARD",
		2: "ABSOLUTE",
	}
	SeekMode_value = map[string]int32{
		"FORWARD":  0,
		"BACKWARD": 1,
		"ABSOLUTE": 2,
	}
)

func (x SeekMode) Enum() *SeekMode {
	p := new(SeekMode)
	*p = x
	return p
}

func (x SeekMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeekMode) Descriptor() protoreflect.EnumDescriptor {
	return file_player_proto_enumTypes[2].Descriptor()
}

func (SeekMode) Type() protoreflect.EnumType {
	return &file_player_proto_enumTypes[2]
}

func (x SeekMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeekMode.Descriptor instead.
func (SeekMode) EnumDescriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Track) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []*Track               `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *QueueRequest) GetQueue() []*Track {
	if x != nil {
		return x.Queue
	}
	return nil
}

type SeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *durationpb.Duration   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Mode          SeekMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=platune.player.v1.SeekMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekRequest) Reset() {
	*x = SeekRequest{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekRequest) ProtoMessage() {}

func (x *SeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekRequest.ProtoReflect.Descriptor instead.
func (*SeekRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *SeekRequest) GetTime() *durationpb.Duration {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *SeekRequest) GetMode() SeekMode {
	if x != nil {
		return x.Mode
	}
	return SeekMode_FORWARD
}

type SetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        float32                `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVolumeRequest) Reset() {
	*x = SetVolumeRequest{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeRequest) ProtoMessage() {}

func (x *SetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeRequest.ProtoReflect.Descriptor instead.
func (*SetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *SetVolumeRequest) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type EventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event Event                  `protobuf:"varint,1,opt,name=event,proto3,enum=platune.player.v1.Event" json:"event,omitempty"`
	// Types that are valid to be assigned to EventPayload:
	//
	//	*EventResponse_State
	//	*EventResponse_SeekData
	//	*EventResponse_Progress
	EventPayload  isEventResponse_EventPayload `protobuf_oneof:"event_payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *EventResponse) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_START_QUEUE
}

func (x *EventResponse) GetEventPayload() isEventResponse_EventPayload {
	if x != nil {
		return x.EventPayload
	}
	return nil
}

func (x *EventResponse) GetState() *State {
	if x != nil {
		if x, ok := x.EventPayload.(*EventResponse_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *EventResponse) GetSeekData() *SeekResponse {
	if x != nil {
		if x, ok := x.EventPayload.(*EventResponse_SeekData); ok {
			return x.SeekData
		}
	}
	return nil
}

func (x *EventResponse) GetProgress() *PositionResponse {
	if x != nil {
		if x, ok := x.EventPayload.(*EventResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isEventResponse_EventPayload interface {
	isEventResponse_EventPayload()
}

type EventResponse_State struct {
	State *State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type EventResponse_SeekData struct {
	SeekData *SeekResponse `protobuf:"bytes,3,opt,name=seek_data,json=seekData,proto3,oneof"`
}

type EventResponse_Progress struct {
	Progress *PositionResponse `protobuf:"bytes,4,opt,name=progress,proto3,oneof"`
}

func (*EventResponse_State) isEventResponse_EventPayload() {}

func (*EventResponse_SeekData) isEventResponse_EventPayload() {}

func (*EventResponse_Progress) isEventResponse_EventPayload() {}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *string                `protobuf:"bytes,1,opt,name=artist,proto3,oneof" json:"artist,omitempty"`
	AlbumArtist   *string                `protobuf:"bytes,2,opt,name=album_artist,json=albumArtist,proto3,oneof" json:"album_artist,omitempty"`
	Album         *string                `protobuf:"bytes,3,opt,name=album,proto3,oneof" json:"album,omitempty"`
	Song          *string                `protobuf:"bytes,4,opt,name=song,proto3,oneof" json:"song,omitempty"`
	TrackNumber   *int64                 `protobuf:"varint,5,opt,name=track_number,json=trackNumber,proto3,oneof" json:"track_number,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,6,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *Metadata) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *Metadata) GetAlbumArtist() string {
	if x != nil && x.AlbumArtist != nil {
		return *x.AlbumArtist
	}
	return ""
}

func (x *Metadata) GetAlbum() string {
	if x != nil && x.Album != nil {
		return *x.Album
	}
	return ""
}

func (x *Metadata) GetSong() string {
	if x != nil && x.Song != nil {
		return *x.Song
	}
	return ""
}

func (x *Metadata) GetTrackNumber() int64 {
	if x != nil && x.TrackNumber != nil {
		return *x.TrackNumber
	}
	return 0
}

func (x *Metadata) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []string               `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	QueuePosition uint32                 `protobuf:"varint,2,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	Status        PlayerStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=platune.player.v1.PlayerStatus" json:"status,omitempty"`
	Volume        float32                `protobuf:"fixed32,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *State) GetQueue() []string {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *State) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *State) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYING
}

func (x *State) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *State) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *durationpb.Duration   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	RetrievalTime *durationpb.Duration   `protobuf:"bytes,2,opt,name=retrieval_time,json=retrievalTime,proto3" json:"retrieval_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{7}
}

func (x *PositionResponse) GetPosition() *durationpb.Duration {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PositionResponse) GetRetrievalTime() *durationpb.Duration {
	if x != nil {
		return x.RetrievalTime
	}
	return nil
}

type SeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SeekMillis    uint64                 `protobuf:"varint,2,opt,name=seek_millis,json=seekMillis,proto3" json:"seek_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekResponse) Reset() {
	*x = SeekResponse{}
	mi := &file_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekResponse) ProtoMessage() {}

func (x *SeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekResponse.ProtoReflect.Descriptor instead.
func (*SeekResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{8}
}

func (x *SeekResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SeekResponse) GetSeekMillis() uint64 {
	if x != nil {
		return x.SeekMillis
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Progress      *PositionResponse      `protobuf:"bytes,2,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StatusResponse) GetProgress() *PositionResponse {
	if x != nil {
		return x.Progress
	}
	return nil
}

type DevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []string               `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicesResponse) Reset() {
	*x = DevicesResponse{}
	mi := &file_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesResponse) ProtoMessage() {}

func (x *DevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesResponse.ProtoReflect.Descriptor instead.
func (*DevicesResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{10}
}

func (x *DevicesResponse) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SetOutputDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *string                `protobuf:"bytes,1,opt,name=device,proto3,oneof" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutputDeviceRequest) Reset() {
	*x = SetOutputDeviceRequest{}
	mi := &file_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputDeviceRequest) ProtoMessage() {}

func (x *SetOutputDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutputDeviceRequest.ProtoReflect.Descriptor instead.
func (*SetOutputDeviceRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{11}
}

func (x *SetOutputDeviceRequest) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\x11platune.player.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"R\n" +
	"\x05Track\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.platune.player.v1.MetadataR\bmetadata\">\n" +
	"\fQueueRequest\x12.\n" +
	"\x05queue\x18\x01 \x03(\v2\x18.platune.player.v1.TrackR\x05queue\"m\n" +
	"\vSeekRequest\x12-\n" +
	"\x04time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x04time\x12/\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1b.platune.player.v1.SeekModeR\x04mode\"*\n" +
	"\x10SetVolumeRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\x02R\x06volume\"\x85\x02\n" +
	"\rEventResponse\x12.\n" +
	"\x05event\x18\x01 \x01(\x0e2\x18.platune.player.v1.EventR\x05event\x120\n" +
	"\x05state\x18\x02 \x01(\v2\x18.platune.player.v1.StateH\x00R\x05state\x12>\n" +
	"\tseek_data\x18\x03 \x01(\v2\x1f.platune.player.v1.SeekResponseH\x00R\bseekData\x12A\n" +
	"\bprogress\x18\x04 \x01(\v2#.platune.player.v1.PositionResponseH\x00R\bprogressB\x0f\n" +
	"\revent_payload\"\xb4\x02\n" +
	"\bMetadata\x12\x1b\n" +
	"\x06artist\x18\x01 \x01(\tH\x00R\x06artist\x88\x01\x01\x12&\n" +
	"\falbum_artist\x18\x02 \x01(\tH\x01R\valbumArtist\x88\x01\x01\x12\x19\n" +
	"\x05album\x18\x03 \x01(\tH\x02R\x05album\x88\x01\x01\x12\x17\n" +
	"\x04song\x18\x04 \x01(\tH\x03R\x04song\x88\x01\x01\x12&\n" +
	"\ftrack_number\x18\x05 \x01(\x03H\x04R\vtrackNumber\x88\x01\x01\x12:\n" +
	"\bduration\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x05R\bduration\x88\x01\x01B\t\n" +
	"\a_artistB\x0f\n" +
	"\r_album_artistB\b\n" +
	"\x06_albumB\a\n" +
	"\x05_songB\x0f\n" +
	"\r_track_numberB\v\n" +
	"\t_duration\"\xe0\x01\n" +
	"\x05State\x12\x14\n" +
	"\x05queue\x18\x01 \x03(\tR\x05queue\x12%\n" +
	"\x0equeue_position\x18\x02 \x01(\rR\rqueuePosition\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.platune.player.v1.PlayerStatusR\x06status\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x02R\x06volume\x12<\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1b.platune.player.v1.MetadataH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x8b\x01\n" +
	"\x10PositionResponse\x125\n" +
	"\bposition\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bposition\x12@\n" +
	"\x0eretrieval_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rretrievalTime\"_\n" +
	"\fSeekResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.platune.player.v1.StateR\x05state\x12\x1f\n" +
	"\vseek_millis\x18\x02 \x01(\x04R\n" +
	"seekMillis\"\x93\x01\n" +
	"\x0eStatusResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.platune.player.v1.StateR\x05state\x12D\n" +
	"\bprogress\x18\x02 \x01(\v2#.platune.player.v1.PositionResponseH\x00R\bprogress\x88\x01\x01B\v\n" +
	"\t_progress\"+\n" +
	"\x0fDevicesResponse\x12\x18\n" +
	"\adevices\x18\x01 \x03(\tR\adevices\"@\n" +
	"\x16SetOutputDeviceRequest\x12\x1b\n" +
	"\x06device\x18\x01 \x01(\tH\x00R\x06device\x88\x01\x01B\t\n" +
	"\a_device*\x98\x01\n" +
	"\x05Event\x12\x0f\n" +
	"\vSTART_QUEUE\x10\x00\x12\x11\n" +
	"\rQUEUE_UPDATED\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\t\n" +
	"\x05PAUSE\x10\x03\x12\n" +
	"\n" +
	"\x06RESUME\x10\x04\x12\x11\n" +
	"\rTRACK_CHANGED\x10\x05\x12\x0e\n" +
	"\n" +
	"SET_VOLUME\x10\x06\x12\b\n" +
	"\x04SEEK\x10\a\x12\x0f\n" +
	"\vQUEUE_ENDED\x10\b\x12\f\n" +
	"\bPOSITION\x10\t*4\n" +
	"\fPlayerStatus\x12\v\n" +
	"\aPLAYING\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02*3\n" +
	"\bSeekMode\x12\v\n" +
	"\aFORWARD\x10\x00\x12\f\n" +
	"\bBACKWARD\x10\x01\x12\f\n" +
	"\bABSOLUTE\x10\x022\xbc\a\n" +
	"\x06Player\x12C\n" +
	"\bSetQueue\x12\x1f.platune.player.v1.QueueRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\n" +
	"AddToQueue\x12\x1f.platune.player.v1.QueueRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x05Pause\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06Resume\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06Toggle\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x04Seek\x12\x1e.platune.player.v1.SeekRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\tSetVolume\x12#.platune.player.v1.SetVolumeRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Next\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bPrevious\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x10GetCurrentStatus\x12\x16.google.protobuf.Empty\x1a!.platune.player.v1.StatusResponse\x12M\n" +
	"\x0fSubscribeEvents\x12\x16.google.protobuf.Empty\x1a .platune.player.v1.EventResponse0\x01\x12O\n" +
	"\x11ListOutputDevices\x12\x16.google.protobuf.Empty\x1a\".platune.player.v1.DevicesResponse\x12T\n" +
	"\x0fSetOutputDevice\x12).platune.player.v1.SetOutputDeviceRequest\x1a\x16.google.protobuf.EmptyBb\n" +
	"\x11platune.player.v1B\vPlayerProtoP\x01Z*github.com/aschey/platune/client/player_v1\xaa\x02\x11Platune.Player.V1b\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_player_proto_goTypes = []any{
	(Event)(0),                     // 0: platune.player.v1.Event
	(PlayerStatus)(0),              // 1: platune.player.v1.PlayerStatus
	(SeekMode)(0),                  // 2: platune.player.v1.SeekMode
	(*Track)(nil),                  // 3: platune.player.v1.Track
	(*QueueRequest)(nil),           // 4: platune.player.v1.QueueRequest
	(*SeekRequest)(nil),            // 5: platune.player.v1.SeekRequest
	(*SetVolumeRequest)(nil),       // 6: platune.player.v1.SetVolumeRequest
	(*EventResponse)(nil),          // 7: platune.player.v1.EventResponse
	(*Metadata)(nil),               // 8: platune.player.v1.Metadata
	(*State)(nil),                  // 9: platune.player.v1.State
	(*PositionResponse)(nil),       // 10: platune.player.v1.PositionResponse
	(*SeekResponse)(nil),           // 11: platune.player.v1.SeekResponse
	(*StatusResponse)(nil),         // 12: platune.player.v1.StatusResponse
	(*DevicesResponse)(nil),        // 13: platune.player.v1.DevicesResponse
	(*SetOutputDeviceRequest)(nil), // 14: platune.player.v1.SetOutputDeviceRequest
	(*durationpb.Duration)(nil),    // 15: google.protobuf.Duration
	(*emptypb.Empty)(nil),          // 16: google.protobuf.Empty
}
var file_player_proto_depIdxs = []int32{
	8,  // 0: platune.player.v1.Track.metadata:type_name -> platune.player.v1.Metadata
	3,  // 1: platune.player.v1.QueueRequest.queue:type_name -> platune.player.v1.Track
	15, // 2: platune.player.v1.SeekRequest.time:type_name -> google.protobuf.Duration
	2,  // 3: platune.player.v1.SeekRequest.mode:type_name -> platune.player.v1.SeekMode
	0,  // 4: platune.player.v1.EventResponse.event:type_name -> platune.player.v1.Event
	9,  // 5: platune.player.v1.EventResponse.state:type_name -> platune.player.v1.State
	11, // 6: platune.player.v1.EventResponse.seek_data:type_name -> platune.player.v1.SeekResponse
	10, // 7: platune.player.v1.EventResponse.progress:type_name -> platune.player.v1.PositionResponse
	15, // 8: platune.player.v1.Metadata.duration:type_name -> google.protobuf.Duration
	1,  // 9: platune.player.v1.State.status:type_name -> platune.player.v1.PlayerStatus
	8,  // 10: platune.player.v1.State.metadata:type_name -> platune.player.v1.Metadata
	15, // 11: platune.player.v1.PositionResponse.position:type_name -> google.protobuf.Duration
	15, // 12: platune.player.v1.PositionResponse.retrieval_time:type_name -> google.protobuf.Duration
	9,  // 13: platune.player.v1.SeekResponse.state:type_name -> platune.player.v1.State
	9,  // 14: platune.player.v1.StatusResponse.state:type_name -> platune.player.v1.State
	10, // 15: platune.player.v1.StatusResponse.progress:type_name -> platune.player.v1.PositionResponse
	4,  // 16: platune.player.v1.Player.SetQueue:input_type -> platune.player.v1.QueueRequest
	4,  // 17: platune.player.v1.Player.AddToQueue:input_type -> platune.player.v1.QueueRequest
	16, // 18: platune.player.v1.Player.Pause:input_type -> google.protobuf.Empty
	16, // 19: platune.player.v1.Player.Stop:input_type -> google.protobuf.Empty
	16, // 20: platune.player.v1.Player.Resume:input_type -> google.protobuf.Empty
	16, // 21: platune.player.v1.Player.Toggle:input_type -> google.protobuf.Empty
	5,  // 22: platune.player.v1.Player.Seek:input_type -> platune.player.v1.SeekRequest
	6,  // 23: platune.player.v1.Player.SetVolume:input_type -> platune.player.v1.SetVolumeRequest
	16, // 24: platune.player.v1.Player.Next:input_type -> google.protobuf.Empty
	16, // 25: platune.player.v1.Player.Previous:input_type -> google.protobuf.Empty
	16, // 26: platune.player.v1.Player.GetCurrentStatus:input_type -> google.protobuf.Empty
	16, // 27: platune.player.v1.Player.SubscribeEvents:input_type -> google.protobuf.Empty
	16, // 28: platune.player.v1.Player.ListOutputDevices:input_type -> google.protobuf.Empty
	14, // 29: platune.player.v1.Player.SetOutputDevice:input_type -> platune.player.v1.SetOutputDeviceRequest
	16, // 30: platune.player.v1.Player.SetQueue:output_type -> google.protobuf.Empty
	16, // 31: platune.player.v1.Player.AddToQueue:output_type -> google.protobuf.Empty
	16, // 32: platune.player.v1.Player.Pause:output_type -> google.protobuf.Empty
	16, // 33: platune.player.v1.Player.Stop:output_type -> google.protobuf.Empty
	16, // 34: platune.player.v1.Player.Resume:output_type -> google.protobuf.Empty
	16, // 35: platune.player.v1.Player.Toggle:output_type -> google.protobuf.Empty
	16, // 36: platune.player.v1.Player.Seek:output_type -> google.protobuf.Empty
	16, // 37: platune.player.v1.Player.SetVolume:output_type -> google.protobuf.Empty
	16, // 38: platune.player.v1.Player.Next:output_type -> google.protobuf.Empty
	16, // 39: platune.player.v1.Player.Previous:output_type -> google.protobuf.Empty
	12, // 40: platune.player.v1.Player.GetCurrentStatus:output_type -> platune.player.v1.StatusResponse
	7,  // 41: platune.player.v1.Player.SubscribeEvents:output_type -> platune.player.v1.EventResponse
	13, // 42: platune.player.v1.Player.ListOutputDevices:output_type -> platune.player.v1.DevicesResponse
	16, // 43: platune.player.v1.Player.SetOutputDevice:output_type -> google.protobuf.Empty
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	file_player_proto_msgTypes[4].OneofWrappers = []any{
		(*EventResponse_State)(nil),
		(*EventResponse_SeekData)(nil),
		(*EventResponse_Progress)(nil),
	}
	file_player_proto_msgTypes[5].OneofWrappers = []any{}
	file_player_proto_msgTypes[6].OneofWrappers = []any{}
	file_player_proto_msgTypes[9].OneofWrappers = []any{}
	file_player_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		EnumInfos:         file_player_proto_enumTypes,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
