export interface Theme {
    intentPrimary: string,
    intentSuccess: string,
    intentWarning: string,
    intentDanger: string,
    textMain: string,
    textSecondary: string,
    backgroundMain: string,
    backgroundSecondary: string,
    textSuccess: string,
    textPrimary: string,
    textWarning: string,
    textDanger: string,
    tableBackground: string,
    gridStripe1: string,
    gridStripe2: string,
    navbarBackground: string,
    dialogBackground: string,
    buttonBackground: string,
    gridSelectedBackground: string,
    gridSelectedShadow: string,
    playingRowBackground: string,
    windowControlsColor: string,
    songTimeColor: string,
    visualizerColor: string,
    volumeSliderColor: string,
    songProgressColor1: string,
    songProgressColor2: string,
    omnibarBackground: string,
    [key: string]: string
}

