[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2021"

[lib]
name = "libplatune_player"
path = "src/lib.rs"

[dependencies]
cpal = "0.15"
derivative = "2"
eyre = "0.6"
flume = "0.10"
futures-util = "0.3"
rb = "0.4"
reqwest = { version = "0.11", features = ["stream"] }
rubato = "0.12"
stream-download = { git = "https://github.com/aschey/stream-download-rs", rev = "66c3cf79ac5f6b528bd24b0da064b8b8c2e43a54" }
strum = { version = "0.24", features = ["derive"] }
symphonia = { version = "0.5", features = [
    "aac",
    "flac",
    "mp3",
    "isomp4",
    "wav",
    "ogg",
    "vorbis",
] }
tap = "1"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.68"
ctor = "0.2.2"
futures = "0.3.28"
pretty_assertions = "1.3.0"
rstest = "0.17.0"
spin_sleep = "1.1.1"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
