[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2018"

[lib]
name = "libplatune_player"
path = "src/lib.rs"

[features]
default = ["runtime-tokio"]
dummy = ["rodio/dummy"]
runtime-tokio = ["tokio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.15"
log = "0.4.14"
postage = "0.4.1"
reqwest = {version = "0.11.4", features = ["stream"]}
rodio = {git = "https://github.com/aschey/rodio", rev = "e2ba0a05", default-features = false, features = ["symphonia-all", "vorbis"]}
strum_macros = "0.21.1"
tempfile = "3.2.0"
tokio = {version = "1.8.1", features = ["rt-multi-thread"], optional = true}

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.50"
ctor = "0.1.20"
flexi_logger = "0.18.0"
futures = "0.3.15"
rstest = "0.10.0"
tokio = {version = "1.8.1", features = ["rt-multi-thread", "macros"]}
yansi = "0.5.0"
