[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2021"

[lib]
name = "libplatune_player"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.58"
cpal = "0.13.5"
flume = "0.10.13"
futures-util = "0.3.21"
rb = "0.4.0"
reqwest = {version = "0.11.11", features = ["stream"]}
rubato = "0.12.0"
strum = {version = "0.24.1", features = ["derive"]}
symphonia = {version = "0.5.1", features = ["aac", "flac", "mp3", "isomp4", "wav", "ogg", "vorbis"]}
tap = "1.0.1"
tempfile = "3.3.0"
thiserror = "1.0.31"
tokio = {version = "1.20.0", features = ["rt-multi-thread", "macros"]}
tracing = "0.1.35"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.56"
ctor = "0.1.22"
futures = "0.3.21"
pretty_assertions = "1.2.1"
rstest = "0.15.0"
spin_sleep = "1.1.1"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.14"
