[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2021"

[lib]
name = "libplatune_player"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.53"
cpal = "0.13.5"
flume = "0.10.10"
futures-util = "0.3.19"
rb = "0.4.0"
reqwest = {version = "0.11.9", features = ["stream"]}
rubato = "0.10.0"
strum = {version = "0.23.0", features = ["derive"]}
symphonia = {version = "0.5.0", features = ["aac", "flac", "mp3", "isomp4", "wav", "ogg", "vorbis"]}
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = {version = "1.15.0", features = ["rt-multi-thread", "macros"]}
tracing = "0.1.29"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.52"
ctor = "0.1.21"
futures = "0.3.19"
pretty_assertions = "1.1.0"
rstest = "0.12.0"
spin_sleep = "1.0.0"
tracing-appender = "0.2.0"
tracing-subscriber = "0.3.6"
