[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2021"

[lib]
name = "libplatune_player"
path = "src/lib.rs"

[features]
default = ["runtime-tokio"]
dummy = ["rodio/dummy"]
runtime-tokio = ["tokio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
futures-util = "0.3.19"
reqwest = {version = "0.11.7", features = ["stream"]}
rodio = {git = "https://github.com/aschey/rodio", rev = "61a80073869e850f5d83acde49704168bec9b0b0", default-features = false, features = ["symphonia-all", "vorbis"]}
strum = {version = "0.23.0", features = ["derive"]}
tempfile = "3.2.0"
tokio = {version = "1.15.0", features = ["rt-multi-thread"], optional = true}
tracing = "0.1.29"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.52"
ctor = "0.1.21"
futures = "0.3.19"
rstest = "0.12.0"
tokio = {version = "1.15.0", features = ["rt-multi-thread", "macros"]}
tracing-appender = "0.2.0"
tracing-subscriber = "0.3.3"
